// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.
/* eslint-disable */

export const PROTOCOL_VERSION = 1;

/** Application error codes carried in JSON-RPC error.code. */
export const ErrorCodes = {
  /** A newer keystroke cancelled this request. */
  RequestCancelled: -32800,
  /** search/start got a query with error diagnostics. */
  QueryInvalid: 1001,
  /** A repo has no index yet; partial results still stream. */
  IndexNotReady: 1002,
  /** The file or commit behind a ref is gone. */
  RefStale: 1003,
  /** A shard or database failed a check; a rebuild starts on its own. */
  IndexCorrupt: 1004,
  /** The search hit its time budget and returned what it had. */
  Overloaded: 1005,
} as const;

/** Span is a range of UTF-16 offsets into the raw query text. */
export interface Span {
  start: number;
  end: number;
}

/** Range is a range of UTF-16 offsets into the text shown on screen. */
export interface Range {
  start: number;
  end: number;
}

/** Hit is a matched Range plus the text term that matched, which picks its highlight color. */
export interface Hit {
  start: number;
  end: number;
  termIndex: number;
}

/** OpName is an operator's name, the part before the colon. */
export type OpName = "f" | "repo" | "lang" | "type" | "sym" | "author" | "msg" | "since" | "case" | "count";

/** Match says how a value was written: bare (literal), quoted (phrase), /regex/, or a path glob such as *.go (f: and repo: only). */
export type Match = "literal" | "phrase" | "regex" | "glob";

/** Mode is what a query searches: current files or Git history. */
export type Mode = "workingTree" | "history";

/** Severity is how serious a Diagnostic is; only errors stop a search. */
export type Severity = "error" | "warning";

/** TextEdit replaces a span of the query text. */
export interface TextEdit {
  span: Span;
  newText: string;
}

/** Fix is a titled set of edits that repairs or rewrites the query. */
export interface Fix {
  title: string;
  edits: TextEdit[];
}

/** Diagnostic is a problem the parser found, with fixes the user can apply. */
export interface Diagnostic {
  severity: Severity;
  code: string;
  message: string;
  span: Span;
  fixes: Fix[];
}

/** Resolved is a friendlier label for an operator value, such as an author's full name. */
export interface Resolved {
  label: string;
}

/** Node is one node of the parsed query tree. */
export type Node =
  | {
      kind: "and" | "or";
      children: Node[];
      span: Span;
    }
  | {
      kind: "not";
      child: Node;
      span: Span;
    }
  | {
      kind: "text";
      value: string;
      match: Match;
      termIndex: number;
      span: Span;
    }
  | {
      kind: "op";
      op: OpName;
      value: string;
      match: Match;
      span: Span;
      resolved?: Resolved;
    };

/** Globals are the query-wide operators case:, count: and type:, or null when absent. */
export interface Globals {
  case: "yes" | "no" | null;
  count: number | "all" | null;
  type: "file" | "code" | "commit" | null;
}

/** ParsedQuery is the parser's output: the query tree, its global operators and its diagnostics. */
export interface ParsedQuery {
  version: 1;
  raw: string;
  root: Node | null;
  globals: Globals;
  mode: Mode;
  diagnostics: Diagnostic[];
}

/** Root is a workspace folder; its id is the first 12 hex digits of sha256(path). */
export interface Root {
  id: string;
  path: string;
  name: string;
}

/** Settings are the unifiedSearch.* settings the daemon needs. */
export interface Settings {
  caseSensitive: boolean;
  defaultCount: number;
  historyDepth: "6m" | "2y" | "all";
  symbols: boolean;
  exclude: string[];
  includeIgnored: boolean;
  maxFileSizeKB: number;
  location: string;
}

/** LastCommit is the newest commit that touched a file. */
export interface LastCommit {
  sha: string;
  author: string;
  at: string;
}

/** Person is a commit author. */
export interface Person {
  name: string;
  email: string;
}

/** FileStat is one file changed by a commit. */
export interface FileStat {
  path: string;
  added: number;
  removed: number;
  hiddenByFilter?: boolean;
}

/** SymbolKind is what a symbol definition is. */
export type SymbolKind = "class" | "interface" | "function" | "method" | "type" | "other";

/** ResultItem is one search result: a file name, a code line, a symbol or a commit. */
export type ResultItem =
  | {
      kind: "file";
      ref: string;
      repoId: string;
      path: string;
      nameHits: Range[];
      lastCommit?: LastCommit;
      dirty: boolean;
    }
  | {
      kind: "line";
      ref: string;
      repoId: string;
      path: string;
      line: number;
      text: string;
      hits: Hit[];
    }
  | {
      kind: "symbol";
      ref: string;
      repoId: string;
      path: string;
      line: number;
      name: string;
      symbolKind: SymbolKind;
      hits: Hit[];
    }
  | {
      kind: "commit";
      ref: string;
      repoId: string;
      sha: string;
      subject: string;
      author: Person;
      at: string;
      files: FileStat[];
      diffHits: number;
      matchedTerms: number[];
      subjectHits: Range[];
    };

/** LineHits are the matches on one preview line. */
export interface LineHits {
  line: number;
  ranges: Hit[];
}

/** OutlineSymbol is a definition shown in a file preview's outline. */
export interface OutlineSymbol {
  name: string;
  line: number;
}

/** DiffLine is one line of a diff hunk. */
export interface DiffLine {
  kind: "ctx" | "add" | "del";
  oldNo?: number;
  newNo?: number;
  text: string;
  hits: Hit[];
}

/** Hunk is one hunk of a commit diff. */
export interface Hunk {
  path: string;
  header: string;
  lines: DiffLine[];
}

/** Preview is the right-hand pane's content for a selected result. */
export type Preview =
  | {
      kind: "file";
      path: string;
      firstLine: number;
      lines: string[];
      focusLine: number;
      hits: LineHits[];
      dirtyLines: number[];
      symbols?: OutlineSymbol[];
    }
  | {
      kind: "commit";
      sha: string;
      subject: string;
      body: string;
      author: string;
      at: string;
      files: FileStat[];
      hunks: Hunk[];
    };

/** HiddenNote counts results a filter removed, with a fix that removes the filter. */
export interface HiddenNote {
  reason: "not" | "since" | "case" | "type" | "pathFilter" | "symbol";
  /** The filter as typed, e.g. -f:vendor/ */
  filter: string;
  count: number;
  unit: "matches" | "files" | "commits" | "definitions";
  undo: Fix;
}

/** Completion is an autocomplete suggestion; accepting it applies its edit. */
export interface Completion {
  label: string;
  /** What the suggestion means, in a few words: "Last 2 hours", "Python files". */
  detail: string;
  /** Facts that help choose it, on a second line: "Since 08:04", "14 files · payments-api, web-checkout". */
  context?: string;
  /** A short status shown at the end of the row: "5 files changed", "Indexing 64%". */
  note?: string;
  /** A heading shown above this suggestion; the suggestions after it, up to the next section, belong under it. */
  section?: string;
  insert: Fix;
  group: "operator" | "author" | "repo" | "lang" | "value";
}

/** IndexState is where one index of a repo stands. */
export type IndexState = "ready" | "indexing" | "queued" | "error" | "off";

/** RepoStatus is the indexing state of one repo. */
export interface RepoStatus {
  repoId: string;
  name: string;
  tree: IndexState;
  history: IndexState;
  progress?: number;
  message?: string;
}

/** OpenTarget is where opening a result goes: a file position (path, line, column, length) or a commit (repoId, sha). */
export interface OpenTarget {
  path?: string;
  line?: number;
  column?: number;
  length?: number;
  repoId?: string;
  sha?: string;
}

/** OpenWhere is which editor group a result opens in. */
export type OpenWhere = "current" | "side";

/** InitializeParams start the daemon. */
export interface InitializeParams {
  protocol: number;
  roots: Root[];
  settings: Settings;
}

/** InitializeResult reports the daemon's version and protocol. */
export interface InitializeResult {
  daemonVersion: string;
  protocol: number;
}

/** SetRootsParams replace the workspace folders. */
export interface SetRootsParams {
  roots: Root[];
}

/** SettingsUpdateParams carry changed settings. */
export interface SettingsUpdateParams {
  settings: Settings;
}

/** FileChange is one file event from VS Code's watcher. */
export interface FileChange {
  path: string;
  type: "changed" | "created" | "deleted";
}

/** DidChangeFilesParams forward file events from the host, a fast path ahead of the daemon's own watcher. */
export interface DidChangeFilesParams {
  changes: FileChange[];
}

/** ParseParams ask the daemon to parse the query box. */
export interface ParseParams {
  text: string;
  cursor: number;
}

/** ParseResult is the parsed query plus completions at the cursor. */
export interface ParseResult {
  query: ParsedQuery;
  completions: Completion[];
}

/** SearchStartParams start (or page) a search; the daemon re-parses the text itself. */
export interface SearchStartParams {
  searchId: string;
  text: string;
  cursor?: string;
}

/** SearchResult ends a search after its batches. */
export interface SearchResult {
  total: number;
  truncated: boolean;
  nextCursor?: string;
  hidden: HiddenNote[];
  ms: number;
}

/** SearchBatchParams stream up to 200 results of a running search. */
export interface SearchBatchParams {
  searchId: string;
  items: ResultItem[];
}

/** PreviewParams ask for the preview of a result. */
export interface PreviewParams {
  ref: string;
  contextLines: number;
}

/** OpenResolveParams ask where a result opens. */
export interface OpenResolveParams {
  ref: string;
}

/** IndexStatusResult is the indexing state of every repo. */
export interface IndexStatusResult {
  repos: RepoStatus[];
}

/** RebuildParams name the repo to rebuild, or all when repoId is absent. */
export interface RebuildParams {
  repoId?: string;
}

/** Empty is a message with no fields. */
export type Empty = Record<string, never>;

/** Envelope wraps every message between the webview and the extension host, in both directions. */
export interface Envelope {
  v: 1;
  type: string;
  seq?: number;
  payload: unknown;
}

/** QueryChangedMsg reports the query box after the typing delay. */
export interface QueryChangedMsg {
  text: string;
  cursor: number;
  seq: number;
  /** True when the user dismissed the suggestions (Esc or Enter): search the box exactly as typed, including the word at the cursor. */
  asTyped?: boolean;
}

/** ResultSelectMsg asks for a result's preview. */
export interface ResultSelectMsg {
  ref: string;
}

/** ResultOpenMsg opens a result in an editor. */
export interface ResultOpenMsg {
  ref: string;
  where: OpenWhere;
}

/** ResultsMoreMsg loads the next page of results. */
export interface ResultsMoreMsg {
  searchId: string;
  cursor: string;
}

/** HelpTryMsg runs an example from the help page in the search panel. */
export interface HelpTryMsg {
  query: string;
}

/** RecentRemoveMsg removes a query from the recent list. */
export interface RecentRemoveMsg {
  query: string;
}

/** WelcomeStateMsg is what the welcome page shows: the shortcut preset and what is indexed. */
export interface WelcomeStateMsg {
  preset: "quickOpen" | "findInFiles" | "none";
  historyDepth: "6m" | "2y" | "all";
  symbols: boolean;
  /** Whether keys are written for a Mac (⌘P) or for Windows and Linux (Ctrl+P) */
  mac: boolean;
}

/** WelcomeChooseMsg saves one choice made on the welcome page in the user's settings. */
export interface WelcomeChooseMsg {
  preset?: "quickOpen" | "findInFiles" | "none";
  historyDepth?: "6m" | "2y" | "all";
  symbols?: boolean;
}

/** ParseResultMsg drives the chips, diagnostics, completions and toggles. */
export interface ParseResultMsg {
  seq: number;
  query: ParsedQuery;
  completions: Completion[];
  /** The text the search runs on when it leaves out the word being completed ("Results for timeout keep updating"). Absent when the whole box is searched. */
  searchText?: string;
}

/** SearchBatchMsg appends streamed results. */
export interface SearchBatchMsg {
  seq: number;
  searchId: string;
  items: ResultItem[];
}

/** SearchDoneMsg ends a search: counts, hidden notes, Load more and errors. */
export interface SearchDoneMsg {
  seq: number;
  searchId: string;
  total: number;
  truncated: boolean;
  nextCursor?: string;
  hidden: HiddenNote[];
  ms: number;
  error?: string;
}

/** PreviewResultMsg fills the preview pane; stale means the result no longer exists. */
export interface PreviewResultMsg {
  ref: string;
  preview: Preview | null;
  stale?: boolean;
}

/** IndexStatusMsg drives the header dot and indexing banners. */
export interface IndexStatusMsg {
  repos: RepoStatus[];
}

/** StateRestoreMsg restores the panel's query, recent queries and settings. */
export interface StateRestoreMsg {
  text: string;
  recent: string[];
  settings?: UiSettings;
}

/** UiSettings are the UI-facing settings the host forwards to the webview. */
export interface UiSettings {
  typingDelayMs: number;
  openTrigger: "doubleClick" | "singleClick";
  preview: boolean;
  showParsedQuery: boolean;
  caseSensitive: boolean;
}

/** BannerMsg reports daemon health: restarting, stopped or cleared. */
export interface BannerMsg {
  state: "ok" | "restarting" | "stopped" | "protocolMismatch";
  message?: string;
}

/** Daemon JSON-RPC requests: method -> [params, result]. */
export interface RpcRequests {
  "initialize": [InitializeParams, InitializeResult];
  "query/parse": [ParseParams, ParseResult];
  "search/start": [SearchStartParams, SearchResult];
  "preview/get": [PreviewParams, Preview];
  "open/resolve": [OpenResolveParams, OpenTarget];
  "index/status": [Empty, IndexStatusResult];
  "index/rebuild": [RebuildParams, Empty];
  "shutdown": [Empty, Empty];
}

/** Daemon JSON-RPC notifications: method -> params. */
export interface RpcNotifications {
  "workspace/setRoots": SetRootsParams;
  "workspace/didChangeFiles": DidChangeFilesParams;
  "settings/update": SettingsUpdateParams;
  "search/batch": SearchBatchParams;
  "$/cancelRequest": Empty;
  "index/progress": IndexStatusResult;
  "exit": Empty;
}

/** Search panel messages, webview->host: type -> payload. */
export interface WebviewToHost {
  "query.changed": QueryChangedMsg;
  "result.select": ResultSelectMsg;
  "result.open": ResultOpenMsg;
  "results.more": ResultsMoreMsg;
  "panel.close": Empty;
  "help.open": Empty;
  "help.try": HelpTryMsg;
  "settings.open": Empty;
  "welcome.choose": WelcomeChooseMsg;
  "welcome.shortcut": Empty;
  "welcome.start": Empty;
  "ready": Empty;
  "daemon.restart": Empty;
  "recent.remove": RecentRemoveMsg;
}

/** Search panel messages, host->webview: type -> payload. */
export interface HostToWebview {
  "parse.result": ParseResultMsg;
  "search.batch": SearchBatchMsg;
  "search.done": SearchDoneMsg;
  "preview.result": PreviewResultMsg;
  "index.status": IndexStatusMsg;
  "state.restore": StateRestoreMsg;
  "banner": BannerMsg;
  "focus": Empty;
  "welcome.state": WelcomeStateMsg;
}
