// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.
/* eslint-disable */

export const PROTOCOL_VERSION = 1;

/** Application error codes carried in JSON-RPC error.code. */
export const ErrorCodes = {
  /** A newer keystroke cancelled this request. */
  RequestCancelled: -32800,
  /** search/start got a query with error diagnostics. */
  QueryInvalid: 1001,
  /** A repo has no index yet; partial results still stream. */
  IndexNotReady: 1002,
  /** The file or commit behind a ref is gone. */
  RefStale: 1003,
  /** A shard or database failed a check; a rebuild starts on its own. */
  IndexCorrupt: 1004,
  /** The search hit its time budget and returned what it had. */
  Overloaded: 1005,
} as const;

/** Span is a range of UTF-16 offsets into the raw query text. */
export interface Span {
  start: number;
  end: number;
}

/** MessageLine is one line of a commit message, with what the query's text terms match in it. */
export interface MessageLine {
  text: string;
  hits: Range[];
}

/** Range is a range of UTF-16 offsets into the text shown on screen. */
export interface Range {
  start: number;
  end: number;
}

/** Hit is a matched Range plus the text term that matched, which picks its highlight color. */
export interface Hit {
  start: number;
  end: number;
  termIndex: number;
}

/** OpName is an operator's name, the part before the colon. */
export type OpName = "f" | "repo" | "lang" | "type" | "sym" | "kind" | "ref" | "is" | "content" | "author" | "msg" | "since" | "until" | "case" | "word" | "count" | "order";

/** CaseSetting is how capital letters match when the query has no case: ignored (off), matched (on), or matched only when the query has a capital letter (smart). */
export type CaseSetting = "off" | "on" | "smart";

/** ResultOrder is how current files are sorted: best match first, or by repo, path and line. */
export type ResultOrder = "best" | "path";

/** RankReason is why best-match order put a file where it is: it defines a searched name or is open in the editor, or it was moved down as a test, vendored or generated file. Absent when nothing stands out or the order is path. */
export type RankReason = "definition" | "open" | "test" | "vendored" | "generated";

/** Match says how a value was written: bare (literal), quoted (phrase), /regex/, or a path glob such as *.go (f: and repo: only). */
export type Match = "literal" | "phrase" | "regex" | "glob";

/** Mode is what a query searches: current files or Git history. */
export type Mode = "workingTree" | "history";

/** Severity is how serious a Diagnostic is; only errors stop a search. */
export type Severity = "error" | "warning";

/** TextEdit replaces a span of the query text. */
export interface TextEdit {
  span: Span;
  newText: string;
}

/** Fix is a titled set of edits that repairs or rewrites the query. */
export interface Fix {
  title: string;
  edits: TextEdit[];
}

/** Diagnostic is a problem the parser found, with fixes the user can apply. */
export interface Diagnostic {
  severity: Severity;
  code: string;
  message: string;
  span: Span;
  fixes: Fix[];
}

/** Resolved is a friendlier label for an operator value, such as an author's full name. */
export interface Resolved {
  label: string;
}

/** Node is one node of the parsed query tree. */
export type Node =
  | {
      kind: "and" | "or";
      children: Node[];
      span: Span;
    }
  | {
      kind: "not";
      child: Node;
      span: Span;
    }
  | {
      kind: "text";
      value: string;
      match: Match;
      termIndex: number;
      /** true for a content: term, which matches the text of files (or a commit's changed lines) and never file names or commit messages. */
      contentOnly?: boolean;
      span: Span;
    }
  | {
      kind: "op";
      op: OpName;
      value: string;
      match: Match;
      span: Span;
      resolved?: Resolved;
    };

/** Globals are the query-wide operators case:, word:, count:, type: and order:, or null when absent. */
export interface Globals {
  /** the query's case: value: yes, no or smart (match case only when the query has a capital letter). */
  case: "yes" | "no" | "smart" | null;
  count: number | "all" | null;
  type: "file" | "code" | "commit" | "added" | "removed" | null;
  /** the query's word: value, yes or no; absent when the query doesn't say. */
  word?: "yes" | "no";
  /** the query's order: value, best or path; absent when the query doesn't say. */
  order?: ResultOrder;
}

/** ParsedQuery is the parser's output: the query tree, its global operators and its diagnostics. */
export interface ParsedQuery {
  version: 1;
  raw: string;
  root: Node | null;
  globals: Globals;
  mode: Mode;
  diagnostics: Diagnostic[];
  /** whether a text term, sym: or msg: value has a capital letter, so smart case matches case. In a regex, only literal letters count: \W and \p{Lu} don't. */
  hasCapital?: boolean;
}

/** Root is a workspace folder; its id is the first 12 hex digits of sha256(path). */
export interface Root {
  id: string;
  path: string;
  name: string;
}

/** Settings are the spelunk.* settings the daemon needs. */
export interface Settings {
  /** the spelunk.caseSensitive setting: how a query without case: treats capital letters. */
  caseSensitive: CaseSetting;
  /** the spelunk.wholeWord setting: match text terms only as whole words unless the query says word:no. */
  wholeWord: boolean;
  defaultCount: number;
  historyDepth: "6m" | "2y" | "all";
  symbols: boolean;
  exclude: string[];
  includeIgnored: boolean;
  maxFileSizeKB: number;
  location: string;
  /** the spelunk.order setting: how a query without order: sorts current files. Absent means best. */
  order?: ResultOrder;
}

/** LastCommit is the newest commit that touched a file. */
export interface LastCommit {
  sha: string;
  author: string;
  at: string;
}

/** Person is a commit author. */
export interface Person {
  name: string;
  email: string;
}

/** FileStat is one file changed by a commit. */
export interface FileStat {
  path: string;
  added: number;
  removed: number;
  hiddenByFilter?: boolean;
}

/** SymbolKind is what a symbol definition is. */
export type SymbolKind = "class" | "interface" | "function" | "method" | "type" | "other";

/** ResultItem is one search result: a file name, a code line, a symbol or a commit. */
export type ResultItem =
  | {
      kind: "file";
      ref: string;
      repoId: string;
      path: string;
      nameHits: Range[];
      lastCommit?: LastCommit;
      dirty: boolean;
      rankReason?: RankReason;
    }
  | {
      kind: "line";
      ref: string;
      repoId: string;
      path: string;
      line: number;
      text: string;
      hits: Hit[];
      rankReason?: RankReason;
    }
  | {
      kind: "symbol";
      ref: string;
      repoId: string;
      path: string;
      line: number;
      name: string;
      symbolKind: SymbolKind;
      hits: Hit[];
      rankReason?: RankReason;
    }
  | {
      kind: "commit";
      ref: string;
      repoId: string;
      sha: string;
      subject: string;
      author: Person;
      at: string;
      files: FileStat[];
      diffHits: number;
      matchedTerms: number[];
      subjectHits: Range[];
      /** Whether a text term matched the commit's subject or body. */
      inMessage: boolean;
      /** The first body line a text term matched, sent when the subject has no match. */
      bodyLine?: MessageLine;
    };

/** LineHits are the matches on one preview line. */
export interface LineHits {
  line: number;
  ranges: Hit[];
}

/** OutlineSymbol is a definition shown in a file preview's outline. */
export interface OutlineSymbol {
  name: string;
  line: number;
}

/** DiffLine is one line of a diff hunk. */
export interface DiffLine {
  kind: "ctx" | "add" | "del";
  oldNo?: number;
  newNo?: number;
  text: string;
  hits: Hit[];
}

/** Hunk is one hunk of a commit diff. */
export interface Hunk {
  path: string;
  header: string;
  lines: DiffLine[];
}

/** Preview is the right-hand pane's content for a selected result. */
export type Preview =
  | {
      kind: "file";
      path: string;
      firstLine: number;
      lines: string[];
      focusLine: number;
      hits: LineHits[];
      dirtyLines: number[];
      symbols?: OutlineSymbol[];
    }
  | {
      kind: "commit";
      sha: string;
      subject: string;
      body: string;
      author: string;
      at: string;
      files: FileStat[];
      hunks: Hunk[];
      subjectHits: Range[];
      bodyHits: Range[];
    };

/** Facet counts a search's results by one field, biggest bucket first, for the buttons that narrow the results. */
export interface Facet {
  field: "repo" | "lang" | "folder" | "author" | "month";
  buckets: FacetBucket[];
  /** How many smaller buckets were left out */
  more: number;
}

/** FacetBucket is one value of a facet: how many results have it, and the filter that keeps only them. */
export interface FacetBucket {
  /** The value as shown, e.g. payments-api, Python, src/, Jane Doe, Sep 2026 */
  label: string;
  count: number;
  /** The filter that keeps only this bucket, as it would be typed, e.g. repo:payments-api; a - before it leaves the bucket out */
  filter: string;
}

/** HiddenNote counts results a filter removed, with a fix that removes the filter. */
export interface HiddenNote {
  reason: "not" | "since" | "case" | "word" | "type" | "pathFilter" | "symbol" | "kind";
  /** The filter as typed, e.g. -f:vendor/ */
  filter: string;
  count: number;
  unit: "matches" | "files" | "commits" | "definitions";
  undo: Fix;
}

/** Completion is an autocomplete suggestion; accepting it applies its edit. */
export interface Completion {
  label: string;
  /** What the suggestion means, in a few words: "Last 2 hours", "Python files". */
  detail: string;
  /** Facts that help choose it, on a second line: "Since 08:04", "14 files · payments-api, web-checkout". */
  context?: string;
  /** A short status shown at the end of the row: "5 files changed", "Indexing 64%". */
  note?: string;
  /** A heading shown above this suggestion; the suggestions after it, up to the next section, belong under it. */
  section?: string;
  insert: Fix;
  group: "operator" | "author" | "repo" | "lang" | "value";
}

/** IndexState is where one index of a repo stands. */
export type IndexState = "ready" | "indexing" | "queued" | "error" | "off";

/** RepoStatus is the indexing state of one repo. */
export interface RepoStatus {
  repoId: string;
  name: string;
  tree: IndexState;
  history: IndexState;
  progress?: number;
  message?: string;
}

/** OpenTarget is where opening a result goes: a file position (path, line, column, length) or a commit (repoId, sha). */
export interface OpenTarget {
  path?: string;
  line?: number;
  column?: number;
  length?: number;
  repoId?: string;
  sha?: string;
}

/** OpenWhere is which editor group a result opens in. */
export type OpenWhere = "current" | "side";

/** InitializeParams start the daemon. */
export interface InitializeParams {
  protocol: number;
  roots: Root[];
  settings: Settings;
}

/** InitializeResult reports the daemon's version and protocol. */
export interface InitializeResult {
  daemonVersion: string;
  protocol: number;
}

/** SetRootsParams replace the workspace folders. */
export interface SetRootsParams {
  roots: Root[];
}

/** SettingsUpdateParams carry changed settings. */
export interface SettingsUpdateParams {
  settings: Settings;
}

/** FileChange is one file event from VS Code's watcher. */
export interface FileChange {
  path: string;
  type: "changed" | "created" | "deleted";
}

/** DidChangeFilesParams forward file events from the host, a fast path ahead of the daemon's own watcher. */
export interface DidChangeFilesParams {
  changes: FileChange[];
}

/** ParseParams ask the daemon to parse the query box. */
export interface ParseParams {
  text: string;
  cursor: number;
  /** the absolute paths of the files open in editor tabs, for is:open. */
  openFiles?: string[];
}

/** ParseResult is the parsed query plus completions at the cursor. */
export interface ParseResult {
  query: ParsedQuery;
  completions: Completion[];
}

/** SearchStartParams start (or page) a search; the daemon re-parses the text itself. */
export interface SearchStartParams {
  searchId: string;
  text: string;
  cursor?: string;
  /** the absolute paths of the files open in editor tabs, for is:open. */
  openFiles?: string[];
}

/** SearchResult ends a search after its batches. */
export interface SearchResult {
  total: number;
  truncated: boolean;
  nextCursor?: string;
  hidden: HiddenNote[];
  facets?: Facet[];
  ms: number;
}

/** SearchBatchParams stream up to 200 results of a running search. */
export interface SearchBatchParams {
  searchId: string;
  items: ResultItem[];
}

/** PreviewParams ask for the preview of a result. */
export interface PreviewParams {
  ref: string;
  contextLines: number;
}

/** OpenResolveParams ask where a result opens. */
export interface OpenResolveParams {
  ref: string;
}

/** IndexStatusResult is the indexing state of every repo. */
export interface IndexStatusResult {
  repos: RepoStatus[];
}

/** RebuildParams name the repo to rebuild, or all when repoId is absent. */
export interface RebuildParams {
  repoId?: string;
}

/** ReplacePlanParams ask for every edit that replacing the query's matches in current files would make. */
export interface ReplacePlanParams {
  text: string;
  /** the text each match becomes; for a /regex/ term, $1 or ${name} insert what a group matched. */
  replacement: string;
  /** the absolute paths of the files open in editor tabs, for is:open. */
  openFiles?: string[];
}

/** ReplaceEdit replaces one match: a range of UTF-16 offsets into the whole line. */
export interface ReplaceEdit {
  start: number;
  end: number;
  newText: string;
}

/** ReplaceLine is one line to edit: its 1-based number, its whole text as indexed (without the line end), and its edits in order. */
export interface ReplaceLine {
  line: number;
  text: string;
  edits: ReplaceEdit[];
}

/** ReplaceFile is one file to edit, with its absolute path. */
export interface ReplaceFile {
  repoId: string;
  path: string;
  file: string;
  lines: ReplaceLine[];
}

/** ReplacePlan is every edit a replace would make. When it would make more than the daemon plans at once, truncated is set and files is empty. */
export interface ReplacePlan {
  matches: number;
  files: ReplaceFile[];
  truncated: boolean;
}

/** Empty is a message with no fields. */
export type Empty = Record<string, never>;

/** Envelope wraps every message between the webview and the extension host, in both directions. */
export interface Envelope {
  v: 1;
  type: string;
  seq?: number;
  payload: unknown;
}

/** QueryChangedMessage reports the query box after the typing delay. */
export interface QueryChangedMessage {
  text: string;
  cursor: number;
  seq: number;
  /** True when the user dismissed the suggestions (Esc or Enter): search the box exactly as typed, including the word at the cursor. */
  asTyped?: boolean;
}

/** ResultSelectMessage asks for a result's preview. */
export interface ResultSelectMessage {
  ref: string;
}

/** ResultOpenMessage opens a result in an editor. */
export interface ResultOpenMessage {
  ref: string;
  where: OpenWhere;
}

/** ResultsMoreMessage loads the next page of results. */
export interface ResultsMoreMessage {
  searchId: string;
  cursor: string;
}

/** HelpTryMessage runs an example from the help page in the search panel. */
export interface HelpTryMessage {
  query: string;
}

/** PinnedQuery is a query starred in the empty box, with the name it was given, if any. */
export interface PinnedQuery {
  query: string;
  name?: string;
}

/** PinnedRemoveMessage unpins a query. */
export interface PinnedRemoveMessage {
  query: string;
}

/** RecentRemoveMessage removes a query from the recent list. */
export interface RecentRemoveMessage {
  query: string;
}

/** ReplacePreviewMessage asks what replacing the query's matches with replacement would change. */
export interface ReplacePreviewMessage {
  seq: number;
  text: string;
  replacement: string;
}

/** ReplaceApplyMessage replaces the matches its preview showed; matches is how many that was, so a plan that changed since is not applied. */
export interface ReplaceApplyMessage {
  seq: number;
  text: string;
  replacement: string;
  matches: number;
}

/** WelcomeStateMessage is what the welcome page shows: the shortcut preset and what is indexed. */
export interface WelcomeStateMessage {
  preset: "quickOpen" | "findInFiles" | "none";
  historyDepth: "6m" | "2y" | "all";
  symbols: boolean;
  /** Whether keys are written for a Mac (⌘P) or for Windows and Linux (Ctrl+P) */
  mac: boolean;
}

/** WelcomeChooseMessage saves one choice made on the welcome page in the user's settings. */
export interface WelcomeChooseMessage {
  preset?: "quickOpen" | "findInFiles" | "none";
  historyDepth?: "6m" | "2y" | "all";
  symbols?: boolean;
}

/** ParseResultMessage drives the chips, diagnostics, completions and toggles. */
export interface ParseResultMessage {
  seq: number;
  query: ParsedQuery;
  completions: Completion[];
  /** The text the search runs on when it leaves out the word being completed ("Results for timeout keep updating"). Absent when the whole box is searched. */
  searchText?: string;
}

/** SearchBatchMessage appends streamed results. */
export interface SearchBatchMessage {
  seq: number;
  searchId: string;
  items: ResultItem[];
}

/** SearchDoneMessage ends a search: counts, hidden notes, Load more and errors. */
export interface SearchDoneMessage {
  seq: number;
  searchId: string;
  total: number;
  truncated: boolean;
  nextCursor?: string;
  hidden: HiddenNote[];
  facets?: Facet[];
  ms: number;
  error?: string;
}

/** PreviewResultMessage fills the preview pane; stale means the result no longer exists. */
export interface PreviewResultMessage {
  ref: string;
  preview: Preview | null;
  stale?: boolean;
}

/** IndexStatusMessage drives the header dot and indexing banners. */
export interface IndexStatusMessage {
  repos: RepoStatus[];
}

/** StateRestoreMessage restores the panel's query, recent and pinned queries, and settings. */
export interface StateRestoreMessage {
  text: string;
  recent: string[];
  pinned: PinnedQuery[];
  settings?: UiSettings;
}

/** UiSettings are the UI-facing settings the host forwards to the webview. */
export interface UiSettings {
  typingDelayMs: number;
  openTrigger: "doubleClick" | "singleClick";
  preview: boolean;
  showParsedQuery: boolean;
  caseSensitive: CaseSetting;
  wholeWord: boolean;
  order: ResultOrder;
}

/** ReplacePlanMessage is the preview of a replace: the edits it would make, or why it can't. */
export interface ReplacePlanMessage {
  seq: number;
  plan?: ReplacePlan;
  error?: string;
}

/** ReplaceDoneMessage says what a replace changed. skipped lists the files left alone because their text no longer matched the index; changed means the matches differed from the preview, so nothing was replaced. */
export interface ReplaceDoneMessage {
  seq: number;
  replaced: number;
  files: number;
  skipped: string[];
  changed?: boolean;
  error?: string;
}

/** BannerMessage reports daemon health: restarting, stopped or cleared. */
export interface BannerMessage {
  state: "ok" | "restarting" | "stopped" | "protocolMismatch";
  message?: string;
}

/** Daemon JSON-RPC requests: method -> [params, result]. */
export interface RpcRequests {
  "initialize": [InitializeParams, InitializeResult];
  "query/parse": [ParseParams, ParseResult];
  "search/start": [SearchStartParams, SearchResult];
  "preview/get": [PreviewParams, Preview];
  "open/resolve": [OpenResolveParams, OpenTarget];
  "index/status": [Empty, IndexStatusResult];
  "index/rebuild": [RebuildParams, Empty];
  "replace/plan": [ReplacePlanParams, ReplacePlan];
  "shutdown": [Empty, Empty];
}

/** Daemon JSON-RPC notifications: method -> params. */
export interface RpcNotifications {
  "workspace/setRoots": SetRootsParams;
  "workspace/didChangeFiles": DidChangeFilesParams;
  "settings/update": SettingsUpdateParams;
  "search/batch": SearchBatchParams;
  "$/cancelRequest": Empty;
  "index/progress": IndexStatusResult;
  "exit": Empty;
}

/** Search panel messages, webview->host: type -> payload. */
export interface WebviewToHost {
  "query.changed": QueryChangedMessage;
  "result.select": ResultSelectMessage;
  "result.open": ResultOpenMessage;
  "results.more": ResultsMoreMessage;
  "panel.close": Empty;
  "help.open": Empty;
  "help.try": HelpTryMessage;
  "settings.open": Empty;
  "welcome.choose": WelcomeChooseMessage;
  "welcome.shortcut": Empty;
  "welcome.start": Empty;
  "ready": Empty;
  "daemon.restart": Empty;
  "recent.remove": RecentRemoveMessage;
  "pinned.save": PinnedQuery;
  "pinned.remove": PinnedRemoveMessage;
  "replace.preview": ReplacePreviewMessage;
  "replace.apply": ReplaceApplyMessage;
  "replace.save": Empty;
}

/** Search panel messages, host->webview: type -> payload. */
export interface HostToWebview {
  "parse.result": ParseResultMessage;
  "search.batch": SearchBatchMessage;
  "search.done": SearchDoneMessage;
  "preview.result": PreviewResultMessage;
  "index.status": IndexStatusMessage;
  "state.restore": StateRestoreMessage;
  "banner": BannerMessage;
  "focus": Empty;
  "welcome.state": WelcomeStateMessage;
  "replace.plan": ReplacePlanMessage;
  "replace.done": ReplaceDoneMessage;
}
