// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.
/* eslint-disable */

export const PROTOCOL_VERSION = 1;

/** UTF-16 offsets into the raw query. */
export interface Span {
  start: number;
  end: number;
}

/** UTF-16 offsets in the shown text. */
export interface Range {
  start: number;
  end: number;
}

/** A matched range plus which text term matched, for colors. */
export interface Hit {
  start: number;
  end: number;
  termIndex: number;
}

export type OpName = "f" | "repo" | "lang" | "type" | "sym" | "author" | "msg" | "since" | "case" | "count";

export type Match = "literal" | "phrase" | "regex";

export type Mode = "workingTree" | "history";

export type Severity = "error" | "warning";

export interface TextEdit {
  span: Span;
  newText: string;
}

export interface Fix {
  title: string;
  edits: TextEdit[];
}

export interface Diagnostic {
  severity: Severity;
  code: string;
  message: string;
  span: Span;
  fixes: Fix[];
}

export interface Resolved {
  label: string;
}

export type Node =
  | {
      kind: "and" | "or";
      children: Node[];
      span: Span;
    }
  | {
      kind: "not";
      child: Node;
      span: Span;
    }
  | {
      kind: "text";
      value: string;
      match: Match;
      termIndex: number;
      span: Span;
    }
  | {
      kind: "op";
      op: OpName;
      value: string;
      match: Match;
      span: Span;
      resolved?: Resolved;
    };

export interface Globals {
  case: "yes" | "no" | null;
  count: number | "all" | null;
  type: "file" | "code" | "commit" | null;
}

export interface ParsedQuery {
  version: 1;
  raw: string;
  root: Node | null;
  globals: Globals;
  mode: Mode;
  diagnostics: Diagnostic[];
}

/** A workspace folder. id = first 12 hex of sha256(path). */
export interface Root {
  id: string;
  path: string;
  name: string;
}

/** The unifiedSearch.* settings the daemon needs (Contract 5). */
export interface Settings {
  caseSensitive: boolean;
  defaultCount: number;
  historyDepth: "6m" | "2y" | "all";
  symbols: boolean;
  exclude: string[];
  includeIgnored: boolean;
  maxFileSizeKB: number;
  location: string;
}

export interface LastCommit {
  sha: string;
  author: string;
  at: string;
}

export interface Person {
  name: string;
  email: string;
}

export interface FileStat {
  path: string;
  added: number;
  removed: number;
  hiddenByFilter?: boolean;
}

export type SymbolKind = "class" | "interface" | "function" | "method" | "type" | "other";

export type ResultItem =
  | {
      kind: "file";
      ref: string;
      repoId: string;
      path: string;
      nameHits: Range[];
      lastCommit?: LastCommit;
      dirty: boolean;
    }
  | {
      kind: "line";
      ref: string;
      repoId: string;
      path: string;
      line: number;
      text: string;
      hits: Hit[];
    }
  | {
      kind: "symbol";
      ref: string;
      repoId: string;
      path: string;
      line: number;
      name: string;
      symbolKind: SymbolKind;
      hits: Hit[];
    }
  | {
      kind: "commit";
      ref: string;
      repoId: string;
      sha: string;
      subject: string;
      author: Person;
      at: string;
      files: FileStat[];
      diffHits: number;
      matchedTerms: number[];
      subjectHits: Range[];
    };

export interface LineHits {
  line: number;
  ranges: Hit[];
}

export interface OutlineSymbol {
  name: string;
  line: number;
}

export interface DiffLine {
  kind: "ctx" | "add" | "del";
  oldNo?: number;
  newNo?: number;
  text: string;
  hits: Hit[];
}

export interface Hunk {
  path: string;
  header: string;
  lines: DiffLine[];
}

export type Preview =
  | {
      kind: "file";
      path: string;
      firstLine: number;
      lines: string[];
      focusLine: number;
      hits: LineHits[];
      dirtyLines: number[];
      symbols?: OutlineSymbol[];
    }
  | {
      kind: "commit";
      sha: string;
      subject: string;
      body: string;
      author: string;
      at: string;
      files: FileStat[];
      hunks: Hunk[];
    };

export interface HiddenNote {
  reason: "not" | "since" | "case" | "type" | "pathFilter";
  count: number;
  unit: "matches" | "files" | "commits";
  undo: Fix;
}

export interface Completion {
  label: string;
  detail: string;
  insert: Fix;
  group: "operator" | "author" | "repo" | "lang" | "value";
}

export type IndexState = "ready" | "indexing" | "queued" | "error" | "off";

export interface RepoStatus {
  repoId: string;
  name: string;
  tree: IndexState;
  history: IndexState;
  progress?: number;
  message?: string;
}

/** Either a file position (path, line, column, length) or a commit (repoId, sha, path). */
export interface OpenTarget {
  path?: string;
  line?: number;
  column?: number;
  length?: number;
  repoId?: string;
  sha?: string;
}

export interface InitializeParams {
  protocol: number;
  roots: Root[];
  settings: Settings;
}

export interface InitializeResult {
  daemonVersion: string;
  protocol: number;
}

export interface SetRootsParams {
  roots: Root[];
}

export interface SettingsUpdateParams {
  settings: Settings;
}

export interface FileChange {
  path: string;
  type: "changed" | "created" | "deleted";
}

/** Host -> daemon: file events from VS Code's watcher, a fast path ahead of the daemon's own watcher. */
export interface DidChangeFilesParams {
  changes: FileChange[];
}

export interface ParseParams {
  text: string;
  cursor: number;
}

export interface ParseResult {
  query: ParsedQuery;
  completions: Completion[];
}

export interface SearchStartParams {
  searchId: string;
  text: string;
  cursor?: string;
}

export interface SearchResult {
  total: number;
  truncated: boolean;
  nextCursor?: string;
  hidden: HiddenNote[];
  ms: number;
}

export interface SearchBatchParams {
  searchId: string;
  items: ResultItem[];
}

export interface PreviewParams {
  ref: string;
  contextLines: number;
}

export interface OpenResolveParams {
  ref: string;
}

export interface IndexStatusResult {
  repos: RepoStatus[];
}

export interface RebuildParams {
  repoId?: string;
}

export type Empty = Record<string, never>;

/** Contract 2 message envelope, sent with postMessage in both directions. */
export interface Envelope {
  v: 1;
  type: string;
  seq?: number;
  payload: unknown;
}

export interface QueryChangedMsg {
  text: string;
  cursor: number;
  seq: number;
}

export interface ResultSelectMsg {
  ref: string;
}

export interface ResultOpenMsg {
  ref: string;
  where: "current" | "side";
}

export interface ResultsMoreMsg {
  searchId: string;
  cursor: string;
}

export interface ParseResultMsg {
  seq: number;
  query: ParsedQuery;
  completions: Completion[];
}

export interface SearchBatchMsg {
  seq: number;
  searchId: string;
  items: ResultItem[];
}

export interface SearchDoneMsg {
  seq: number;
  searchId: string;
  total: number;
  truncated: boolean;
  nextCursor?: string;
  hidden: HiddenNote[];
  ms: number;
  error?: string;
}

export interface PreviewResultMsg {
  ref: string;
  preview: Preview | null;
  stale?: boolean;
}

export interface IndexStatusMsg {
  repos: RepoStatus[];
}

export interface StateRestoreMsg {
  text: string;
  recent: string[];
  settings?: UiSettings;
}

/** The UI-facing settings the host forwards to the webview. */
export interface UiSettings {
  typingDelayMs: number;
  openTrigger: "doubleClick" | "singleClick";
  preview: boolean;
  showParsedQuery: boolean;
  caseSensitive: boolean;
}

/** Daemon health banner (failure table): restarting, stopped, or cleared. */
export interface BannerMsg {
  state: "ok" | "restarting" | "stopped" | "protocolMismatch";
  message?: string;
}

/** Contract 3 requests: method -> [params, result]. */
export interface RpcRequests {
  "initialize": [InitializeParams, InitializeResult];
  "query/parse": [ParseParams, ParseResult];
  "search/start": [SearchStartParams, SearchResult];
  "preview/get": [PreviewParams, Preview];
  "open/resolve": [OpenResolveParams, OpenTarget];
  "index/status": [Empty, IndexStatusResult];
  "index/rebuild": [RebuildParams, Empty];
  "shutdown": [Empty, Empty];
}

/** Contract 3 notifications: method -> params. */
export interface RpcNotifications {
  "workspace/setRoots": SetRootsParams;
  "workspace/didChangeFiles": DidChangeFilesParams;
  "settings/update": SettingsUpdateParams;
  "search/batch": SearchBatchParams;
  "$/cancelRequest": Empty;
  "index/progress": IndexStatusResult;
  "exit": Empty;
}

/** Contract 2 messages, webview->host: type -> payload. */
export interface WebviewToHost {
  "query.changed": QueryChangedMsg;
  "result.select": ResultSelectMsg;
  "result.open": ResultOpenMsg;
  "results.more": ResultsMoreMsg;
  "panel.close": Empty;
  "help.open": Empty;
  "settings.open": Empty;
  "ready": Empty;
  "daemon.restart": Empty;
}

/** Contract 2 messages, host->webview: type -> payload. */
export interface HostToWebview {
  "parse.result": ParseResultMsg;
  "search.batch": SearchBatchMsg;
  "search.done": SearchDoneMsg;
  "preview.result": PreviewResultMsg;
  "index.status": IndexStatusMsg;
  "state.restore": StateRestoreMsg;
  "banner": BannerMsg;
  "focus": Empty;
}
