#!/usr/bin/env node
// Generates TypeScript and Go types from protocol.schema.json.
// Usage: node protocol/gen.mjs [--check]
// --check exits non-zero when a generated file is out of date (CI).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");
const schema = JSON.parse(readFileSync(join(here, "protocol.schema.json"), "utf8"));
const defs = schema.$defs;
const version = schema["x-protocol-version"];
const methods = schema["x-rpc-methods"];
const messages = schema["x-webview-messages"];

const refName = (r) => r.replace("#/$defs/", "");
const isNull = (s) => s && s.type === "null";
const nullableInner = (s) => {
  const alts = s.oneOf || s.anyOf;
  if (!alts) return null;
  const non = alts.filter((a) => !isNull(a));
  return non.length !== alts.length ? non : null;
};
const isObjUnion = (s) => (s.oneOf || []).length > 1 && s.oneOf.every((v) => v.type === "object" && v.properties?.kind);
const pascal = (s) => s.replace(/(^|[^A-Za-z0-9]+)([A-Za-z0-9])/g, (_, __, c) => c.toUpperCase());
const goField = (s) => {
  const p = pascal(s);
  return p.replace(/Id$/, "ID").replace(/^Id$/, "ID").replace(/Kb$/, "KB").replace(/Sha$/, "SHA").replace(/Ms$/, "Ms");
};

// ---------------- TypeScript ----------------
function tsType(s) {
  if (s.$ref) return refName(s.$ref);
  if (s["x-ts-type"]) return s["x-ts-type"];
  const nn = nullableInner(s);
  if (nn) return [...nn.map(tsType), "null"].join(" | ");
  if (s.oneOf || s.anyOf) return (s.oneOf || s.anyOf).map(tsType).join(" | ");
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((e) => JSON.stringify(e)).join(" | ");
  switch (s.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const t = tsType(s.items);
      return /[|&]/.test(t) ? `(${t})[]` : `${t}[]`;
    }
    case "object":
      return tsObject(s, "  ");
  }
  throw new Error("tsType: unsupported " + JSON.stringify(s));
}
function tsObject(s, indent) {
  const req = new Set(s.required || []);
  const props = Object.entries(s.properties || {});
  if (!props.length) return "Record<string, never>";
  const lines = props.map(([k, v]) => `${indent}${k}${req.has(k) ? "" : "?"}: ${tsType(v)};`);
  return `{\n${lines.join("\n")}\n${indent.slice(2)}}`;
}
function genTS() {
  const out = [
    "// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.",
    "/* eslint-disable */",
    "",
    `export const PROTOCOL_VERSION = ${version};`,
    "",
  ];
  for (const [name, s] of Object.entries(defs)) {
    if (s.description) out.push(`/** ${s.description} */`);
    if (s.type === "object" && !s["x-ts-type"]) {
      const body = tsObject(s, "  ");
      out.push(body.startsWith("{") ? `export interface ${name} ${body}` : `export type ${name} = ${body};`);
    } else if (isObjUnion(s)) {
      out.push(`export type ${name} =\n` + s.oneOf.map((v) => `  | ${tsObject(v, "      ")}`).join("\n") + ";");
    } else {
      out.push(`export type ${name} = ${tsType(s)};`);
    }
    out.push("");
  }
  out.push("/** Contract 3 requests: method -> [params, result]. */");
  out.push("export interface RpcRequests {");
  for (const [m, d] of Object.entries(methods))
    if (d.kind === "request") out.push(`  ${JSON.stringify(m)}: [${d.params}, ${d.result}];`);
  out.push("}", "");
  out.push("/** Contract 3 notifications: method -> params. */");
  out.push("export interface RpcNotifications {");
  for (const [m, d] of Object.entries(methods))
    if (d.kind === "notification") out.push(`  ${JSON.stringify(m)}: ${d.params};`);
  out.push("}", "");
  for (const [dir, iface] of [
    ["webview->host", "WebviewToHost"],
    ["host->webview", "HostToWebview"],
  ]) {
    out.push(`/** Contract 2 messages, ${dir}: type -> payload. */`);
    out.push(`export interface ${iface} {`);
    for (const [t, d] of Object.entries(messages))
      if (d.direction === dir) out.push(`  ${JSON.stringify(t)}: ${d.payload};`);
    out.push("}", "");
  }
  return out.join("\n");
}

// ---------------- Go ----------------
const goNamed = new Set(); // defs that become named Go types
for (const [n, s] of Object.entries(defs)) goNamed.add(n);

function goType(s, { optional = false } = {}) {
  if (s["x-go-type"]) return s["x-go-type"];
  if (s.$ref) {
    const n = refName(s.$ref);
    const d = defs[n];
    const isStruct = d.type === "object" || isObjUnion(d);
    return optional && isStruct ? "*" + n : n;
  }
  const nn = nullableInner(s);
  if (nn) {
    if (nn.length !== 1) return "any";
    const t = goType(nn[0]);
    return t.startsWith("*") || t.startsWith("[]") || t === "any" ? t : "*" + t;
  }
  if (s.oneOf || s.anyOf) return "any";
  if (s.const !== undefined) return typeof s.const === "number" ? "int" : "string";
  if (s.enum) return "string";
  switch (s.type) {
    case "string":
      return "string";
    case "integer":
      return "int";
    case "number":
      return "float64";
    case "boolean":
      return "bool";
    case "array":
      return "[]" + goType(s.items);
    case "object":
      return "map[string]any";
  }
  throw new Error("goType: unsupported " + JSON.stringify(s));
}
const zeroCheck = (t, expr) => {
  if (t.startsWith("*") || t === "any" || t.startsWith("map[")) return `${expr} != nil`;
  if (t.startsWith("[]")) return `len(${expr}) > 0`;
  if (t === "string" || (/^[A-Z]/.test(t) && defs[t] && defs[t].type === "string")) return `${expr} != ""`;
  if (t === "int" || t === "float64") return `${expr} != 0`;
  if (t === "bool") return expr;
  return null;
};

function genGo() {
  const out = [
    "// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.",
    "",
    "package protocol",
    "",
    'import "encoding/json"',
    "",
    `// Version is the protocol version exchanged in initialize.`,
    `const Version = ${version}`,
    "",
    "var _ json.RawMessage",
    "",
  ];
  for (const [name, s] of Object.entries(defs)) {
    if (s.description) out.push(`// ${name}: ${s.description}`);
    if (s.type === "object") {
      const req = new Set(s.required || []);
      const fields = Object.entries(s.properties || {});
      out.push(`type ${name} struct {`);
      const sliceFix = [];
      for (const [k, v] of fields) {
        const opt = !req.has(k);
        const t = goType(v, { optional: opt });
        out.push(`\t${goField(k)} ${t} \`json:"${k}${opt ? ",omitempty" : ""}"\``);
        if (!opt && t.startsWith("[]")) sliceFix.push([goField(k), t]);
      }
      out.push("}", "");
      if (sliceFix.length) {
        out.push(`// MarshalJSON emits [] rather than null for required arrays.`);
        out.push(`func (v ${name}) MarshalJSON() ([]byte, error) {`, `\ttype alias ${name}`, `\ta := alias(v)`);
        for (const [f, t] of sliceFix) out.push(`\tif a.${f} == nil {`, `\t\ta.${f} = ${t}{}`, `\t}`);
        out.push(`\treturn json.Marshal(a)`, `}`, "");
      }
    } else if (isObjUnion(s)) {
      // Merge variants into one struct; MarshalJSON emits only the fields of
      // the variant selected by Kind, with [] for required arrays.
      const merged = new Map();
      for (const v of s.oneOf)
        for (const [k, p] of Object.entries(v.properties)) {
          const t = k === "kind" ? "string" : goType(p, { optional: !(v.required || []).includes(k) || k === "child" });
          const prev = merged.get(k);
          if (prev && prev !== t && !(prev.replace("*", "") === t.replace("*", "")))
            throw new Error(`${name}.${k}: conflicting types ${prev} vs ${t}`);
          if (!prev || t.startsWith("*")) merged.set(k, t);
        }
      out.push(`type ${name} struct {`);
      for (const [k, t] of merged) out.push(`\t${goField(k)} ${t} \`json:"${k},omitempty"\``);
      out.push("}", "");
      out.push(`// MarshalJSON emits the fields of the variant named by Kind.`);
      out.push(
        `func (v ${name}) MarshalJSON() ([]byte, error) {`,
        `\tm := map[string]any{"kind": v.Kind}`,
        `\tswitch v.Kind {`,
      );
      for (const variant of s.oneOf) {
        const kinds =
          variant.properties.kind.const !== undefined ? [variant.properties.kind.const] : variant.properties.kind.enum;
        out.push(`\tcase ${kinds.map((k) => JSON.stringify(k)).join(", ")}:`);
        const req = new Set(variant.required || []);
        for (const k of Object.keys(variant.properties)) {
          if (k === "kind") continue;
          const t = merged.get(k),
            f = `v.${goField(k)}`;
          if (req.has(k)) {
            if (t.startsWith("[]"))
              out.push(
                `\t\tif ${f} == nil {`,
                `\t\t\tm[${JSON.stringify(k)}] = ${t}{}`,
                `\t\t} else {`,
                `\t\t\tm[${JSON.stringify(k)}] = ${f}`,
                `\t\t}`,
              );
            else out.push(`\t\tm[${JSON.stringify(k)}] = ${f}`);
          } else {
            const zc = zeroCheck(t, f);
            out.push(
              zc ? `\t\tif ${zc} {\n\t\t\tm[${JSON.stringify(k)}] = ${f}\n\t\t}` : `\t\tm[${JSON.stringify(k)}] = ${f}`,
            );
          }
        }
      }
      out.push(`\t}`, `\treturn json.Marshal(m)`, `}`, "");
    } else if (s.enum && s.type === "string") {
      out.push(`type ${name} = string`, "");
      out.push("const (");
      for (const e of s.enum) out.push(`\t${name}${pascal(e)} ${name} = ${JSON.stringify(e)}`);
      out.push(")", "");
    } else {
      out.push(`type ${name} = ${goType(s)}`, "");
    }
  }
  out.push("// Contract 3 method names.", "const (");
  for (const m of Object.keys(methods))
    out.push(`\tMethod${pascal(m.replace("$/", "Dollar/"))} = ${JSON.stringify(m)}`);
  out.push(")", "");
  out.push("// Contract 2 message types.", "const (");
  for (const t of Object.keys(messages)) out.push(`\tMsg${pascal(t)} = ${JSON.stringify(t)}`);
  out.push(")", "");
  out.push("// SpecMethods lists every Contract 3 method, for spec coverage.");
  out.push(
    "var SpecMethods = []string{" +
      Object.keys(methods)
        .map((m) => JSON.stringify(m))
        .join(", ") +
      "}",
    "",
  );
  out.push("// SpecMessages lists every Contract 2 message type, for spec coverage.");
  out.push(
    "var SpecMessages = []string{" +
      Object.keys(messages)
        .map((m) => JSON.stringify(m))
        .join(", ") +
      "}",
    "",
  );
  return out.join("\n");
}

function gofmt(src) {
  try {
    return execFileSync("gofmt", [], { input: src, encoding: "utf8" });
  } catch (e) {
    if (e.code === "ENOENT") return src; // no Go toolchain: leave unformatted
    throw e;
  }
}

const targets = [
  [join(repo, "extension/src/protocol.gen.ts"), genTS()],
  [join(repo, "webview/src/protocol.gen.ts"), genTS()],
  [join(repo, "daemon/internal/protocol/protocol_gen.go"), gofmt(genGo())],
];
const check = process.argv.includes("--check");
let stale = 0;
for (const [path, text] of targets) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== text) {
      console.error("out of date: " + path);
      stale++;
    }
  } else {
    writeFileSync(path, text);
    console.log("wrote " + path.replace(repo + "/", ""));
  }
}
process.exit(stale ? 1 : 0);
