#!/usr/bin/env node
// Generates the TypeScript and Go types for every cross-process message from
// protocol.schema.json (see docs/adr/0002-json-schema-as-protocol-source.md).
//
// Usage: node protocol/gen.mjs [--check]
//   --check writes nothing and exits non-zero when a generated file is stale.
//
// Only the schema features the protocol uses are supported: objects, arrays,
// string enums and consts, nullable alternatives (oneOf [X, null]), and unions
// of objects discriminated by a `kind` property. Anything else throws.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const schema = JSON.parse(readFileSync(join(here, "protocol.schema.json"), "utf8"));
const definitions = schema.$defs;
const protocolVersion = schema["x-protocol-version"];
const rpcMethods = schema["x-rpc-methods"];
const webviewMessages = schema["x-webview-messages"];
const errorCodes = schema["x-error-codes"];

/** Go initialisms keep one case (Go Code Review Comments). */
const GO_INITIALISMS = { Id: "ID", Kb: "KB", Sha: "SHA", Url: "URL", Uri: "URI", Json: "JSON" };

// ------------------------------------------------------------ schema helpers

const refName = (ref) => ref.replace("#/$defs/", "");
const isNullSchema = (node) => node?.type === "null";

/** For `oneOf: [X, {type: null}]`, the non-null alternatives; otherwise null. */
function nonNullAlternatives(node) {
  const alternatives = node.oneOf ?? node.anyOf;
  if (!alternatives) return null;
  const nonNull = alternatives.filter((alt) => !isNullSchema(alt));
  return nonNull.length !== alternatives.length ? nonNull : null;
}

/** A union of objects told apart by their `kind` property. */
function isKindUnion(node) {
  const variants = node.oneOf ?? [];
  return variants.length > 1 && variants.every((v) => v.type === "object" && v.properties?.kind);
}

const pascalCase = (text) => text.replace(/(^|[^A-Za-z0-9]+)([A-Za-z0-9])/g, (_, _sep, letter) => letter.toUpperCase());

/** A JSON property name as a Go field name: repoId -> RepoID. */
function goFieldName(property) {
  const words = pascalCase(property).match(/[A-Z][a-z0-9]*/g) ?? [pascalCase(property)];
  return words.map((word) => GO_INITIALISMS[word] ?? word).join("");
}

// ------------------------------------------------------------ TypeScript

function tsType(node) {
  if (node.$ref) return refName(node.$ref);
  if (node["x-ts-type"]) return node["x-ts-type"];
  const nonNull = nonNullAlternatives(node);
  if (nonNull) return [...nonNull.map(tsType), "null"].join(" | ");
  if (node.oneOf || node.anyOf) return (node.oneOf ?? node.anyOf).map(tsType).join(" | ");
  if (node.const !== undefined) return JSON.stringify(node.const);
  if (node.enum) return node.enum.map((value) => JSON.stringify(value)).join(" | ");
  switch (node.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const item = tsType(node.items);
      return /[|&]/.test(item) ? `(${item})[]` : `${item}[]`;
    }
    case "object":
      return tsObjectLiteral(node, "  ");
  }
  throw new Error("tsType: unsupported schema " + JSON.stringify(node));
}

function tsObjectLiteral(node, indent) {
  const required = new Set(node.required ?? []);
  const properties = Object.entries(node.properties ?? {});
  if (!properties.length) return "Record<string, never>";
  const fields = properties.map(([name, property]) => {
    const doc = property.description ? `${indent}/** ${property.description} */\n` : "";
    return `${doc}${indent}${name}${required.has(name) ? "" : "?"}: ${tsType(property)};`;
  });
  return `{\n${fields.join("\n")}\n${indent.slice(2)}}`;
}

function generateTypeScript() {
  const lines = [
    "// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.",
    "/* eslint-disable */",
    "",
    `export const PROTOCOL_VERSION = ${protocolVersion};`,
    "",
    "/** Application error codes carried in JSON-RPC error.code. */",
    "export const ErrorCodes = {",
    ...Object.entries(errorCodes).map(([name, { code, when }]) => `  /** ${when}. */\n  ${name}: ${code},`),
    "} as const;",
    "",
  ];
  for (const [name, node] of Object.entries(definitions)) {
    lines.push(`/** ${node.description} */`);
    if (node.type === "object" && !node["x-ts-type"]) {
      const body = tsObjectLiteral(node, "  ");
      lines.push(body.startsWith("{") ? `export interface ${name} ${body}` : `export type ${name} = ${body};`);
    } else if (isKindUnion(node)) {
      lines.push(
        `export type ${name} =\n` + node.oneOf.map((v) => `  | ${tsObjectLiteral(v, "      ")}`).join("\n") + ";",
      );
    } else {
      lines.push(`export type ${name} = ${tsType(node)};`);
    }
    lines.push("");
  }
  lines.push("/** Daemon JSON-RPC requests: method -> [params, result]. */", "export interface RpcRequests {");
  for (const [method, entry] of Object.entries(rpcMethods)) {
    if (entry.kind === "request") lines.push(`  ${JSON.stringify(method)}: [${entry.params}, ${entry.result}];`);
  }
  lines.push("}", "", "/** Daemon JSON-RPC notifications: method -> params. */", "export interface RpcNotifications {");
  for (const [method, entry] of Object.entries(rpcMethods)) {
    if (entry.kind === "notification") lines.push(`  ${JSON.stringify(method)}: ${entry.params};`);
  }
  lines.push("}", "");
  for (const [direction, interfaceName] of [
    ["webview->host", "WebviewToHost"],
    ["host->webview", "HostToWebview"],
  ]) {
    lines.push(`/** Search panel messages, ${direction}: type -> payload. */`, `export interface ${interfaceName} {`);
    for (const [type, entry] of Object.entries(webviewMessages)) {
      if (entry.direction === direction) lines.push(`  ${JSON.stringify(type)}: ${entry.payload};`);
    }
    lines.push("}", "");
  }
  return lines.join("\n");
}

// ------------------------------------------------------------ Go

const isGoStruct = (definition) => definition.type === "object" || isKindUnion(definition);
const stripPointer = (goType) => goType.replace(/^\*/, "");

/** The Go type for a schema node. Optional structs become pointers so they can be omitted. */
function goType(node, { optional = false } = {}) {
  if (node["x-go-type"]) return node["x-go-type"];
  if (node.$ref) {
    const name = refName(node.$ref);
    return optional && isGoStruct(definitions[name]) ? "*" + name : name;
  }
  const nonNull = nonNullAlternatives(node);
  if (nonNull) {
    if (nonNull.length !== 1) return "any";
    const inner = goType(nonNull[0]);
    const alreadyNullable = inner.startsWith("*") || inner.startsWith("[]") || inner === "any";
    return alreadyNullable ? inner : "*" + inner;
  }
  if (node.oneOf || node.anyOf) return "any";
  if (node.const !== undefined) return typeof node.const === "number" ? "int" : "string";
  if (node.enum) return "string";
  switch (node.type) {
    case "string":
      return "string";
    case "integer":
      return "int";
    case "number":
      return "float64";
    case "boolean":
      return "bool";
    case "array":
      return "[]" + goType(node.items);
    case "object":
      return "map[string]any";
  }
  throw new Error("goType: unsupported schema " + JSON.stringify(node));
}

/** A Go expression that is true when `fieldExpr` holds a non-zero value, or null if always present. */
function nonZeroCheck(goTypeName, fieldExpr) {
  if (goTypeName.startsWith("*") || goTypeName === "any" || goTypeName.startsWith("map[")) return `${fieldExpr} != nil`;
  if (goTypeName.startsWith("[]")) return `len(${fieldExpr}) > 0`;
  const isNamedString = definitions[goTypeName]?.type === "string";
  if (goTypeName === "string" || isNamedString) return `${fieldExpr} != ""`;
  if (goTypeName === "int" || goTypeName === "float64") return `${fieldExpr} != 0`;
  if (goTypeName === "bool") return fieldExpr;
  return null;
}

function goDocComment(text) {
  return `// ${text}`;
}

function generateGoStruct(name, node) {
  const required = new Set(node.required ?? []);
  const lines = [goDocComment(node.description), `type ${name} struct {`];
  const requiredSlices = [];
  for (const [property, propertyNode] of Object.entries(node.properties ?? {})) {
    const optional = !required.has(property);
    const fieldType = goType(propertyNode, { optional });
    const field = goFieldName(property);
    if (propertyNode.description) lines.push(`\t// ${field} is ${lowerFirst(propertyNode.description)}`);
    lines.push(`\t${field} ${fieldType} \`json:"${property}${optional ? ",omitempty" : ""}"\``);
    if (!optional && fieldType.startsWith("[]")) requiredSlices.push([field, fieldType]);
  }
  lines.push("}", "");
  if (requiredSlices.length) {
    lines.push(`// MarshalJSON emits [] rather than null for required arrays.`);
    lines.push(`func (v ${name}) MarshalJSON() ([]byte, error) {`, `\ttype plain ${name}`, `\tp := plain(v)`);
    for (const [field, fieldType] of requiredSlices)
      lines.push(`\tif p.${field} == nil {`, `\t\tp.${field} = ${fieldType}{}`, `\t}`);
    lines.push(`\treturn json.Marshal(p)`, `}`, "");
  }
  return lines;
}

/**
 * A kind-union becomes one Go struct holding every variant's fields. Its
 * MarshalJSON writes only the fields of the variant named by Kind, with []
 * for required arrays, so the wire format matches the TypeScript union.
 */
function generateGoUnion(name, node) {
  const fieldTypes = new Map();
  for (const variant of node.oneOf) {
    const required = new Set(variant.required ?? []);
    for (const [property, propertyNode] of Object.entries(variant.properties)) {
      // A recursive field (Node.child) must be a pointer, so it is always optional in Go.
      const optional = !required.has(property) || property === "child";
      const fieldType = property === "kind" ? "string" : goType(propertyNode, { optional });
      const previous = fieldTypes.get(property);
      if (previous && stripPointer(previous) !== stripPointer(fieldType)) {
        throw new Error(`${name}.${property}: variants disagree on its type (${previous} vs ${fieldType})`);
      }
      if (!previous || fieldType.startsWith("*")) fieldTypes.set(property, fieldType);
    }
  }
  const lines = [goDocComment(node.description), `type ${name} struct {`];
  for (const [property, fieldType] of fieldTypes)
    lines.push(`\t${goFieldName(property)} ${fieldType} \`json:"${property},omitempty"\``);
  lines.push("}", "");
  lines.push(`// MarshalJSON emits only the fields of the variant named by Kind.`);
  lines.push(
    `func (v ${name}) MarshalJSON() ([]byte, error) {`,
    `\tfields := map[string]any{"kind": v.Kind}`,
    `\tswitch v.Kind {`,
  );
  for (const variant of node.oneOf) {
    const kinds =
      variant.properties.kind.const !== undefined ? [variant.properties.kind.const] : variant.properties.kind.enum;
    lines.push(`\tcase ${kinds.map((kind) => JSON.stringify(kind)).join(", ")}:`);
    const required = new Set(variant.required ?? []);
    for (const property of Object.keys(variant.properties)) {
      if (property === "kind") continue;
      const fieldType = fieldTypes.get(property);
      const fieldExpr = `v.${goFieldName(property)}`;
      const key = JSON.stringify(property);
      if (required.has(property) && fieldType.startsWith("[]")) {
        lines.push(
          `\t\tif ${fieldExpr} == nil {`,
          `\t\t\tfields[${key}] = ${fieldType}{}`,
          `\t\t} else {`,
          `\t\t\tfields[${key}] = ${fieldExpr}`,
          `\t\t}`,
        );
      } else if (required.has(property)) {
        lines.push(`\t\tfields[${key}] = ${fieldExpr}`);
      } else {
        const check = nonZeroCheck(fieldType, fieldExpr);
        lines.push(
          check ? `\t\tif ${check} {\n\t\t\tfields[${key}] = ${fieldExpr}\n\t\t}` : `\t\tfields[${key}] = ${fieldExpr}`,
        );
      }
    }
  }
  lines.push(`\t}`, `\treturn json.Marshal(fields)`, `}`, "");
  return lines;
}

function generateGoEnum(name, node) {
  return [
    goDocComment(node.description),
    `type ${name} = string`,
    "",
    `// ${name} values.`,
    "const (",
    ...node.enum.map((value) => `\t${name}${pascalCase(value)} ${name} = ${JSON.stringify(value)}`),
    ")",
    "",
  ];
}

function generateGo() {
  const lines = [
    "// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.",
    "",
    "package protocol",
    "",
    'import "encoding/json"',
    "",
    `// Version is the protocol version exchanged in initialize.`,
    `const Version = ${protocolVersion}`,
    "",
    "// Application error codes carried in JSON-RPC error.code.",
    "const (",
    ...Object.entries(errorCodes).map(
      ([name, { code, when }]) => `\t// Code${name}: ${when}.\n\tCode${name} = ${code}`,
    ),
    ")",
    "",
  ];
  for (const [name, node] of Object.entries(definitions)) {
    if (!node.description?.startsWith(name))
      throw new Error(`${name}: description must start with "${name}" (it becomes the doc comment)`);
    if (node.type === "object") lines.push(...generateGoStruct(name, node));
    else if (isKindUnion(node)) lines.push(...generateGoUnion(name, node));
    else if (node.enum && node.type === "string") lines.push(...generateGoEnum(name, node));
    else lines.push(goDocComment(node.description), `type ${name} = ${goType(node)}`, "");
  }
  lines.push("// Daemon JSON-RPC method names.", "const (");
  for (const method of Object.keys(rpcMethods))
    lines.push(`\tMethod${pascalCase(method.replace("$/", "Dollar/"))} = ${JSON.stringify(method)}`);
  lines.push(")", "", "// Search panel message types (webview <-> extension host).", "const (");
  for (const type of Object.keys(webviewMessages)) lines.push(`\tMsg${pascalCase(type)} = ${JSON.stringify(type)}`);
  lines.push(")", "");
  return lines.join("\n");
}

function lowerFirst(text) {
  return text.charAt(0).toLowerCase() + text.slice(1);
}

/** Formats Go source with gofmt when a Go toolchain is installed. */
function gofmt(source) {
  try {
    return execFileSync("gofmt", [], { input: source, encoding: "utf8" });
  } catch (error) {
    if (error.code === "ENOENT") return source;
    throw error;
  }
}

// ------------------------------------------------------------ write or check

const typescript = generateTypeScript();
const outputs = [
  [join(repoRoot, "extension/src/protocol.gen.ts"), typescript],
  [join(repoRoot, "webview/src/protocol.gen.ts"), typescript],
  [join(repoRoot, "daemon/internal/protocol/protocol_gen.go"), gofmt(generateGo())],
];
const checkOnly = process.argv.includes("--check");
let staleCount = 0;
for (const [path, content] of outputs) {
  const relativePath = path.replace(repoRoot + "/", "");
  if (!checkOnly) {
    writeFileSync(path, content);
    console.log("wrote " + relativePath);
  } else if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
    console.error("out of date: " + relativePath + " (run node protocol/gen.mjs)");
    staleCount++;
  }
}
process.exit(staleCount ? 1 : 0);
