package trigram

import (
	"reflect"
	"slices"
	"strconv"
	"testing"
	"time"

	"github.com/cruisinme30/spelunk/daemon/internal/protocol"
	"github.com/cruisinme30/spelunk/daemon/internal/symbols"
)

// rankedRepo has a file of each kind best-match order tells apart.
func rankedRepo() Repo {
	repo := repoOf("app", map[string]string{
		"src/backoff.py":      "# waits before retrying\n",
		"src/client.py":       "from retry import retry\n\nretry(call)\n",
		"src/retry.py":        "def retry(call):\n    return call()\n",
		"src/retry_policy.py": "class RetryPolicy:\n    pass\n",
		"tests/retry_test.py": "from retry import retry\n",
		"vendor/lib/retry.js": "function retry() {}\n",
		"gen/api.pb.go":       "// Code generated by protoc. DO NOT EDIT.\npackage api\n\nfunc retry() {}\n",
	})
	withSymbols(repo.Shard)
	return repo
}

// withSymbols extracts each doc's definitions, as Build does with index.symbols.
func withSymbols(shard *Shard) {
	for i := range shard.Docs {
		doc := &shard.Docs[i]
		doc.Symbols = symbols.Extract(doc.Lang, doc.Content)
	}
}

// files lists each result's kind and path once, in the order they came.
func files(items []protocol.ResultItem) []string {
	var out []string
	for _, item := range items {
		if entry := item.Kind + " " + item.Path; !slices.Contains(out, entry) {
			out = append(out, entry)
		}
	}
	return out
}

// reasons maps each result's path to its rank reason, where it has one.
func reasons(items []protocol.ResultItem) map[string]string {
	out := map[string]string{}
	for _, item := range items {
		if item.RankReason != "" {
			out[item.Path] = item.RankReason
		}
	}
	return out
}

func TestBestMatchPutsDefinitionsAndNamesFirstAndTestsVendoredAndGeneratedLast(t *testing.T) {
	items, _ := runItems(t, "retry", bestMatchSettings, "", rankedRepo())
	want := []string{
		"file src/retry.py",        // defines retry and is named after it
		"file src/retry_policy.py", // has retry as a word of its name
		"file tests/retry_test.py", // a test
		"file vendor/lib/retry.js", // vendored, below tests
		"line src/retry.py",
		"line src/retry_policy.py",
		"line src/client.py",  // whole-word, exact-case lines
		"line src/backoff.py", // retrying: neither
		"line tests/retry_test.py",
		"line vendor/lib/retry.js", // vendored and generated are one tier, kept by score
		"line gen/api.pb.go",
	}
	if got := files(items); !reflect.DeepEqual(got, want) {
		t.Errorf("order:\n got %q\nwant %q", got, want)
	}
	wantReasons := map[string]string{
		"src/retry.py":        protocol.RankReasonDefinition,
		"tests/retry_test.py": protocol.RankReasonTest,
		"vendor/lib/retry.js": protocol.RankReasonVendored,
		"gen/api.pb.go":       protocol.RankReasonGenerated,
	}
	if got := reasons(items); !reflect.DeepEqual(got, wantReasons) {
		t.Errorf("reasons = %v, want %v", got, wantReasons)
	}
}

func TestOrderPathKeepsResultsInPathOrder(t *testing.T) {
	// @covers op:order setting:order
	byOperator, _ := runItems(t, "order:path retry", bestMatchSettings, "", rankedRepo())
	bySetting, _ := runItems(t, "retry", defaultSettings, "", rankedRepo())
	want := []string{
		"file src/retry.py", "file src/retry_policy.py", "file tests/retry_test.py", "file vendor/lib/retry.js",
		"line gen/api.pb.go", "line src/backoff.py", "line src/client.py", "line src/retry.py",
		"line src/retry_policy.py", "line tests/retry_test.py", "line vendor/lib/retry.js",
	}
	if got := files(byOperator); !reflect.DeepEqual(got, want) {
		t.Errorf("order:path:\n got %q\nwant %q", got, want)
	}
	if got := files(bySetting); !reflect.DeepEqual(got, want) {
		t.Errorf("order setting path:\n got %q\nwant %q", got, want)
	}
	if got := reasons(byOperator); len(got) != 0 {
		t.Errorf("reasons = %v, want none in path order", got)
	}
}

func TestBestMatchKeepsEachFilesLinesTogetherAndInLineOrder(t *testing.T) {
	items, _ := runItems(t, "retry", bestMatchSettings, "", rankedRepo())
	var client []int
	for _, item := range items {
		if item.Path == "src/client.py" && item.Kind == "line" {
			client = append(client, item.Line)
		}
	}
	if want := []int{1, 3}; !reflect.DeepEqual(client, want) {
		t.Errorf("src/client.py lines = %v, want %v", client, want)
	}
}

func TestBestMatchPagesNeverRepeatOrSkipAResult(t *testing.T) {
	all, stats := runItems(t, "retry", bestMatchSettings, "", rankedRepo())
	var paged []protocol.ResultItem
	for cursor := ""; ; {
		page, pageStats := runItems(t, "count:3 retry", bestMatchSettings, cursor, rankedRepo())
		paged = append(paged, page...)
		if pageStats.NextOffset == 0 {
			break
		}
		cursor = strconv.Itoa(pageStats.NextOffset)
	}
	if len(paged) != stats.Total {
		t.Fatalf("pages hold %d results, want %d", len(paged), stats.Total)
	}
	if got, want := refs(paged), refs(all); !sameElements(got, want) {
		t.Errorf("pages hold\n %q\nwant the same results as one page\n %q", got, want)
	}
}

func refs(items []protocol.ResultItem) []string {
	out := make([]string, len(items))
	for i, item := range items {
		out[i] = item.Ref
	}
	return out
}

func sameElements(a, b []string) bool {
	a, b = slices.Clone(a), slices.Clone(b)
	slices.Sort(a)
	slices.Sort(b)
	return slices.Equal(a, b) && len(slices.Compact(a)) == len(b)
}

func TestBestMatchPutsUncommittedThenRecentlyChangedFilesFirst(t *testing.T) {
	repo := repoOf("app", map[string]string{
		"a.py": "timeout = 1\n",
		"b.py": "timeout = 2\n",
		"c.py": "timeout = 3\n",
	})
	repo.History = fakeHistory{
		dirty:   map[string]bool{"c.py": true},
		changed: map[string]time.Time{"a.py": time.Now().Add(-90 * 24 * time.Hour), "b.py": time.Now().Add(-time.Hour)},
	}
	items, _ := runItems(t, "timeout", bestMatchSettings, "", repo)
	if got, want := files(items), []string{"line c.py", "line b.py", "line a.py"}; !reflect.DeepEqual(got, want) {
		t.Errorf("order = %q, want %q (uncommitted, then changed an hour ago, then three months ago)", got, want)
	}
}

func TestWholeWordAndExactCaseLinesRankAFileHigherWithinAPage(t *testing.T) {
	repo := repoOf("app", map[string]string{
		"a.py": "retrying = True\n",
		"b.py": "RETRY = 3\n",
		"c.py": "retry(call)\n",
	})
	items, _ := runItems(t, "retry", bestMatchSettings, "", repo)
	if got, want := files(items), []string{"line c.py", "line b.py", "line a.py"}; !reflect.DeepEqual(got, want) {
		t.Errorf("order = %q, want %q (whole word in its own case, whole word, part of a word)", got, want)
	}
}

func TestADefinitionMustBeTheWholeName(t *testing.T) {
	repo := repoOf("app", map[string]string{
		"a.py": "class RetryPolicy:\n    pass\n",
		"b.py": "def retry_later():\n    retry_policy = None\n",
	})
	withSymbols(repo.Shard)
	items, _ := runItems(t, "/retry.?policy/", bestMatchSettings, "", repo)
	if got := reasons(items); !reflect.DeepEqual(got, map[string]string{"a.py": protocol.RankReasonDefinition}) {
		t.Errorf("reasons = %v, want only a.py, whose RetryPolicy the regex matches whole", got)
	}
}

func TestVendoredAndGeneratedPaths(t *testing.T) {
	if !isVendored("web/node_modules/lodash/index.js") || isVendored("src/vendors.go") {
		t.Error("isVendored should match a node_modules folder and not a file named vendors.go")
	}
	for _, doc := range []Doc{
		{Path: "api/service.pb.go"},
		{Path: "web/app.min.js"},
		{Path: "src/schema.ts", Content: []byte("// @generated by codegen\nexport type A = 1;\n")},
	} {
		if !isGenerated(&doc) {
			t.Errorf("isGenerated(%q) = false, want true", doc.Path)
		}
	}
	if isGenerated(&Doc{Path: "src/gen.go", Content: []byte("// Code generated by hand, edit freely.\n")}) {
		t.Error(`"Code generated" without "DO NOT EDIT" isn't a generated-code marker`)
	}
}

// fakeHistory says which files have uncommitted changes and when the rest
// last changed.
type fakeHistory struct {
	dirty   map[string]bool
	changed map[string]time.Time
}

func (h fakeHistory) LastCommit(path string) (protocol.LastCommit, time.Time, bool) {
	at, ok := h.changed[path]
	return protocol.LastCommit{}, at, ok
}

func (h fakeHistory) Dirty(path string) bool { return h.dirty[path] }
