// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.

package protocol

import "encoding/json"

// Version is the protocol version exchanged in initialize.
const Version = 1

var _ json.RawMessage

// Span: UTF-16 offsets into the raw query.
type Span struct {
	Start int `json:"start"`
	End   int `json:"end"`
}

// Range: UTF-16 offsets in the shown text.
type Range struct {
	Start int `json:"start"`
	End   int `json:"end"`
}

// Hit: A matched range plus which text term matched, for colors.
type Hit struct {
	Start     int `json:"start"`
	End       int `json:"end"`
	TermIndex int `json:"termIndex"`
}

type OpName = string

const (
	OpNameF      OpName = "f"
	OpNameRepo   OpName = "repo"
	OpNameLang   OpName = "lang"
	OpNameType   OpName = "type"
	OpNameSym    OpName = "sym"
	OpNameAuthor OpName = "author"
	OpNameMsg    OpName = "msg"
	OpNameSince  OpName = "since"
	OpNameCase   OpName = "case"
	OpNameCount  OpName = "count"
)

type Match = string

const (
	MatchLiteral Match = "literal"
	MatchPhrase  Match = "phrase"
	MatchRegex   Match = "regex"
)

type Mode = string

const (
	ModeWorkingTree Mode = "workingTree"
	ModeHistory     Mode = "history"
)

type Severity = string

const (
	SeverityError   Severity = "error"
	SeverityWarning Severity = "warning"
)

type TextEdit struct {
	Span    Span   `json:"span"`
	NewText string `json:"newText"`
}

type Fix struct {
	Title string     `json:"title"`
	Edits []TextEdit `json:"edits"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v Fix) MarshalJSON() ([]byte, error) {
	type alias Fix
	a := alias(v)
	if a.Edits == nil {
		a.Edits = []TextEdit{}
	}
	return json.Marshal(a)
}

type Diagnostic struct {
	Severity Severity `json:"severity"`
	Code     string   `json:"code"`
	Message  string   `json:"message"`
	Span     Span     `json:"span"`
	Fixes    []Fix    `json:"fixes"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v Diagnostic) MarshalJSON() ([]byte, error) {
	type alias Diagnostic
	a := alias(v)
	if a.Fixes == nil {
		a.Fixes = []Fix{}
	}
	return json.Marshal(a)
}

type Resolved struct {
	Label string `json:"label"`
}

type Node struct {
	Kind      string    `json:"kind,omitempty"`
	Children  []Node    `json:"children,omitempty"`
	Span      Span      `json:"span,omitempty"`
	Child     *Node     `json:"child,omitempty"`
	Value     string    `json:"value,omitempty"`
	Match     Match     `json:"match,omitempty"`
	TermIndex int       `json:"termIndex,omitempty"`
	Op        OpName    `json:"op,omitempty"`
	Resolved  *Resolved `json:"resolved,omitempty"`
}

// MarshalJSON emits the fields of the variant named by Kind.
func (v Node) MarshalJSON() ([]byte, error) {
	m := map[string]any{"kind": v.Kind}
	switch v.Kind {
	case "and", "or":
		if v.Children == nil {
			m["children"] = []Node{}
		} else {
			m["children"] = v.Children
		}
		m["span"] = v.Span
	case "not":
		m["child"] = v.Child
		m["span"] = v.Span
	case "text":
		m["value"] = v.Value
		m["match"] = v.Match
		m["termIndex"] = v.TermIndex
		m["span"] = v.Span
	case "op":
		m["op"] = v.Op
		m["value"] = v.Value
		m["match"] = v.Match
		m["span"] = v.Span
		if v.Resolved != nil {
			m["resolved"] = v.Resolved
		}
	}
	return json.Marshal(m)
}

type Globals struct {
	Case  *string `json:"case"`
	Count any     `json:"count"`
	Type  *string `json:"type"`
}

type ParsedQuery struct {
	Version     int          `json:"version"`
	Raw         string       `json:"raw"`
	Root        *Node        `json:"root"`
	Globals     Globals      `json:"globals"`
	Mode        Mode         `json:"mode"`
	Diagnostics []Diagnostic `json:"diagnostics"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v ParsedQuery) MarshalJSON() ([]byte, error) {
	type alias ParsedQuery
	a := alias(v)
	if a.Diagnostics == nil {
		a.Diagnostics = []Diagnostic{}
	}
	return json.Marshal(a)
}

// Root: A workspace folder. id = first 12 hex of sha256(path).
type Root struct {
	ID   string `json:"id"`
	Path string `json:"path"`
	Name string `json:"name"`
}

// Settings: The unifiedSearch.* settings the daemon needs (Contract 5).
type Settings struct {
	CaseSensitive  bool     `json:"caseSensitive"`
	DefaultCount   int      `json:"defaultCount"`
	HistoryDepth   string   `json:"historyDepth"`
	Symbols        bool     `json:"symbols"`
	Exclude        []string `json:"exclude"`
	IncludeIgnored bool     `json:"includeIgnored"`
	MaxFileSizeKB  int      `json:"maxFileSizeKB"`
	Location       string   `json:"location"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v Settings) MarshalJSON() ([]byte, error) {
	type alias Settings
	a := alias(v)
	if a.Exclude == nil {
		a.Exclude = []string{}
	}
	return json.Marshal(a)
}

type LastCommit struct {
	SHA    string `json:"sha"`
	Author string `json:"author"`
	At     string `json:"at"`
}

type Person struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type FileStat struct {
	Path           string `json:"path"`
	Added          int    `json:"added"`
	Removed        int    `json:"removed"`
	HiddenByFilter bool   `json:"hiddenByFilter,omitempty"`
}

type SymbolKind = string

const (
	SymbolKindClass     SymbolKind = "class"
	SymbolKindInterface SymbolKind = "interface"
	SymbolKindFunction  SymbolKind = "function"
	SymbolKindMethod    SymbolKind = "method"
	SymbolKindType      SymbolKind = "type"
	SymbolKindOther     SymbolKind = "other"
)

type ResultItem struct {
	Kind         string      `json:"kind,omitempty"`
	Ref          string      `json:"ref,omitempty"`
	RepoID       string      `json:"repoId,omitempty"`
	Path         string      `json:"path,omitempty"`
	NameHits     []Range     `json:"nameHits,omitempty"`
	LastCommit   *LastCommit `json:"lastCommit,omitempty"`
	Dirty        bool        `json:"dirty,omitempty"`
	Line         int         `json:"line,omitempty"`
	Text         string      `json:"text,omitempty"`
	Hits         []Hit       `json:"hits,omitempty"`
	Name         string      `json:"name,omitempty"`
	SymbolKind   SymbolKind  `json:"symbolKind,omitempty"`
	SHA          string      `json:"sha,omitempty"`
	Subject      string      `json:"subject,omitempty"`
	Author       Person      `json:"author,omitempty"`
	At           string      `json:"at,omitempty"`
	Files        []FileStat  `json:"files,omitempty"`
	DiffHits     int         `json:"diffHits,omitempty"`
	MatchedTerms []int       `json:"matchedTerms,omitempty"`
	SubjectHits  []Range     `json:"subjectHits,omitempty"`
}

// MarshalJSON emits the fields of the variant named by Kind.
func (v ResultItem) MarshalJSON() ([]byte, error) {
	m := map[string]any{"kind": v.Kind}
	switch v.Kind {
	case "file":
		m["ref"] = v.Ref
		m["repoId"] = v.RepoID
		m["path"] = v.Path
		if v.NameHits == nil {
			m["nameHits"] = []Range{}
		} else {
			m["nameHits"] = v.NameHits
		}
		if v.LastCommit != nil {
			m["lastCommit"] = v.LastCommit
		}
		m["dirty"] = v.Dirty
	case "line":
		m["ref"] = v.Ref
		m["repoId"] = v.RepoID
		m["path"] = v.Path
		m["line"] = v.Line
		m["text"] = v.Text
		if v.Hits == nil {
			m["hits"] = []Hit{}
		} else {
			m["hits"] = v.Hits
		}
	case "symbol":
		m["ref"] = v.Ref
		m["repoId"] = v.RepoID
		m["path"] = v.Path
		m["line"] = v.Line
		m["name"] = v.Name
		m["symbolKind"] = v.SymbolKind
		if v.Hits == nil {
			m["hits"] = []Hit{}
		} else {
			m["hits"] = v.Hits
		}
	case "commit":
		m["ref"] = v.Ref
		m["repoId"] = v.RepoID
		m["sha"] = v.SHA
		m["subject"] = v.Subject
		m["author"] = v.Author
		m["at"] = v.At
		if v.Files == nil {
			m["files"] = []FileStat{}
		} else {
			m["files"] = v.Files
		}
		m["diffHits"] = v.DiffHits
		if v.MatchedTerms == nil {
			m["matchedTerms"] = []int{}
		} else {
			m["matchedTerms"] = v.MatchedTerms
		}
		if v.SubjectHits == nil {
			m["subjectHits"] = []Range{}
		} else {
			m["subjectHits"] = v.SubjectHits
		}
	}
	return json.Marshal(m)
}

type LineHits struct {
	Line   int   `json:"line"`
	Ranges []Hit `json:"ranges"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v LineHits) MarshalJSON() ([]byte, error) {
	type alias LineHits
	a := alias(v)
	if a.Ranges == nil {
		a.Ranges = []Hit{}
	}
	return json.Marshal(a)
}

type OutlineSymbol struct {
	Name string `json:"name"`
	Line int    `json:"line"`
}

type DiffLine struct {
	Kind  string `json:"kind"`
	OldNo int    `json:"oldNo,omitempty"`
	NewNo int    `json:"newNo,omitempty"`
	Text  string `json:"text"`
	Hits  []Hit  `json:"hits"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v DiffLine) MarshalJSON() ([]byte, error) {
	type alias DiffLine
	a := alias(v)
	if a.Hits == nil {
		a.Hits = []Hit{}
	}
	return json.Marshal(a)
}

type Hunk struct {
	Path   string     `json:"path"`
	Header string     `json:"header"`
	Lines  []DiffLine `json:"lines"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v Hunk) MarshalJSON() ([]byte, error) {
	type alias Hunk
	a := alias(v)
	if a.Lines == nil {
		a.Lines = []DiffLine{}
	}
	return json.Marshal(a)
}

type Preview struct {
	Kind       string          `json:"kind,omitempty"`
	Path       string          `json:"path,omitempty"`
	FirstLine  int             `json:"firstLine,omitempty"`
	Lines      []string        `json:"lines,omitempty"`
	FocusLine  int             `json:"focusLine,omitempty"`
	Hits       []LineHits      `json:"hits,omitempty"`
	DirtyLines []int           `json:"dirtyLines,omitempty"`
	Symbols    []OutlineSymbol `json:"symbols,omitempty"`
	SHA        string          `json:"sha,omitempty"`
	Subject    string          `json:"subject,omitempty"`
	Body       string          `json:"body,omitempty"`
	Author     string          `json:"author,omitempty"`
	At         string          `json:"at,omitempty"`
	Files      []FileStat      `json:"files,omitempty"`
	Hunks      []Hunk          `json:"hunks,omitempty"`
}

// MarshalJSON emits the fields of the variant named by Kind.
func (v Preview) MarshalJSON() ([]byte, error) {
	m := map[string]any{"kind": v.Kind}
	switch v.Kind {
	case "file":
		m["path"] = v.Path
		m["firstLine"] = v.FirstLine
		if v.Lines == nil {
			m["lines"] = []string{}
		} else {
			m["lines"] = v.Lines
		}
		m["focusLine"] = v.FocusLine
		if v.Hits == nil {
			m["hits"] = []LineHits{}
		} else {
			m["hits"] = v.Hits
		}
		if v.DirtyLines == nil {
			m["dirtyLines"] = []int{}
		} else {
			m["dirtyLines"] = v.DirtyLines
		}
		if len(v.Symbols) > 0 {
			m["symbols"] = v.Symbols
		}
	case "commit":
		m["sha"] = v.SHA
		m["subject"] = v.Subject
		m["body"] = v.Body
		m["author"] = v.Author
		m["at"] = v.At
		if v.Files == nil {
			m["files"] = []FileStat{}
		} else {
			m["files"] = v.Files
		}
		if v.Hunks == nil {
			m["hunks"] = []Hunk{}
		} else {
			m["hunks"] = v.Hunks
		}
	}
	return json.Marshal(m)
}

type HiddenNote struct {
	Reason string `json:"reason"`
	Count  int    `json:"count"`
	Unit   string `json:"unit"`
	Undo   Fix    `json:"undo"`
}

type Completion struct {
	Label  string `json:"label"`
	Detail string `json:"detail"`
	Insert Fix    `json:"insert"`
	Group  string `json:"group"`
}

type IndexState = string

const (
	IndexStateReady    IndexState = "ready"
	IndexStateIndexing IndexState = "indexing"
	IndexStateQueued   IndexState = "queued"
	IndexStateError    IndexState = "error"
	IndexStateOff      IndexState = "off"
)

type RepoStatus struct {
	RepoID   string     `json:"repoId"`
	Name     string     `json:"name"`
	Tree     IndexState `json:"tree"`
	History  IndexState `json:"history"`
	Progress float64    `json:"progress,omitempty"`
	Message  string     `json:"message,omitempty"`
}

// OpenTarget: Either a file position (path, line, column, length) or a commit (repoId, sha, path).
type OpenTarget struct {
	Path   string `json:"path,omitempty"`
	Line   int    `json:"line,omitempty"`
	Column int    `json:"column,omitempty"`
	Length int    `json:"length,omitempty"`
	RepoID string `json:"repoId,omitempty"`
	SHA    string `json:"sha,omitempty"`
}

type InitializeParams struct {
	Protocol int      `json:"protocol"`
	Roots    []Root   `json:"roots"`
	Settings Settings `json:"settings"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v InitializeParams) MarshalJSON() ([]byte, error) {
	type alias InitializeParams
	a := alias(v)
	if a.Roots == nil {
		a.Roots = []Root{}
	}
	return json.Marshal(a)
}

type InitializeResult struct {
	DaemonVersion string `json:"daemonVersion"`
	Protocol      int    `json:"protocol"`
}

type SetRootsParams struct {
	Roots []Root `json:"roots"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SetRootsParams) MarshalJSON() ([]byte, error) {
	type alias SetRootsParams
	a := alias(v)
	if a.Roots == nil {
		a.Roots = []Root{}
	}
	return json.Marshal(a)
}

type SettingsUpdateParams struct {
	Settings Settings `json:"settings"`
}

type FileChange struct {
	Path string `json:"path"`
	Type string `json:"type"`
}

// DidChangeFilesParams: Host -> daemon: file events from VS Code's watcher, a fast path ahead of the daemon's own watcher.
type DidChangeFilesParams struct {
	Changes []FileChange `json:"changes"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v DidChangeFilesParams) MarshalJSON() ([]byte, error) {
	type alias DidChangeFilesParams
	a := alias(v)
	if a.Changes == nil {
		a.Changes = []FileChange{}
	}
	return json.Marshal(a)
}

type ParseParams struct {
	Text   string `json:"text"`
	Cursor int    `json:"cursor"`
}

type ParseResult struct {
	Query       ParsedQuery  `json:"query"`
	Completions []Completion `json:"completions"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v ParseResult) MarshalJSON() ([]byte, error) {
	type alias ParseResult
	a := alias(v)
	if a.Completions == nil {
		a.Completions = []Completion{}
	}
	return json.Marshal(a)
}

type SearchStartParams struct {
	SearchID string `json:"searchId"`
	Text     string `json:"text"`
	Cursor   string `json:"cursor,omitempty"`
}

type SearchResult struct {
	Total      int          `json:"total"`
	Truncated  bool         `json:"truncated"`
	NextCursor string       `json:"nextCursor,omitempty"`
	Hidden     []HiddenNote `json:"hidden"`
	Ms         int          `json:"ms"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SearchResult) MarshalJSON() ([]byte, error) {
	type alias SearchResult
	a := alias(v)
	if a.Hidden == nil {
		a.Hidden = []HiddenNote{}
	}
	return json.Marshal(a)
}

type SearchBatchParams struct {
	SearchID string       `json:"searchId"`
	Items    []ResultItem `json:"items"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SearchBatchParams) MarshalJSON() ([]byte, error) {
	type alias SearchBatchParams
	a := alias(v)
	if a.Items == nil {
		a.Items = []ResultItem{}
	}
	return json.Marshal(a)
}

type PreviewParams struct {
	Ref          string `json:"ref"`
	ContextLines int    `json:"contextLines"`
}

type OpenResolveParams struct {
	Ref string `json:"ref"`
}

type IndexStatusResult struct {
	Repos []RepoStatus `json:"repos"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v IndexStatusResult) MarshalJSON() ([]byte, error) {
	type alias IndexStatusResult
	a := alias(v)
	if a.Repos == nil {
		a.Repos = []RepoStatus{}
	}
	return json.Marshal(a)
}

type RebuildParams struct {
	RepoID string `json:"repoId,omitempty"`
}

type Empty struct {
}

// Envelope: Contract 2 message envelope, sent with postMessage in both directions.
type Envelope struct {
	V       int             `json:"v"`
	Type    string          `json:"type"`
	Seq     int             `json:"seq,omitempty"`
	Payload json.RawMessage `json:"payload"`
}

type QueryChangedMsg struct {
	Text   string `json:"text"`
	Cursor int    `json:"cursor"`
	Seq    int    `json:"seq"`
}

type ResultSelectMsg struct {
	Ref string `json:"ref"`
}

type ResultOpenMsg struct {
	Ref   string `json:"ref"`
	Where string `json:"where"`
}

type ResultsMoreMsg struct {
	SearchID string `json:"searchId"`
	Cursor   string `json:"cursor"`
}

type ParseResultMsg struct {
	Seq         int          `json:"seq"`
	Query       ParsedQuery  `json:"query"`
	Completions []Completion `json:"completions"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v ParseResultMsg) MarshalJSON() ([]byte, error) {
	type alias ParseResultMsg
	a := alias(v)
	if a.Completions == nil {
		a.Completions = []Completion{}
	}
	return json.Marshal(a)
}

type SearchBatchMsg struct {
	Seq      int          `json:"seq"`
	SearchID string       `json:"searchId"`
	Items    []ResultItem `json:"items"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SearchBatchMsg) MarshalJSON() ([]byte, error) {
	type alias SearchBatchMsg
	a := alias(v)
	if a.Items == nil {
		a.Items = []ResultItem{}
	}
	return json.Marshal(a)
}

type SearchDoneMsg struct {
	Seq        int          `json:"seq"`
	SearchID   string       `json:"searchId"`
	Total      int          `json:"total"`
	Truncated  bool         `json:"truncated"`
	NextCursor string       `json:"nextCursor,omitempty"`
	Hidden     []HiddenNote `json:"hidden"`
	Ms         int          `json:"ms"`
	Error      string       `json:"error,omitempty"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SearchDoneMsg) MarshalJSON() ([]byte, error) {
	type alias SearchDoneMsg
	a := alias(v)
	if a.Hidden == nil {
		a.Hidden = []HiddenNote{}
	}
	return json.Marshal(a)
}

type PreviewResultMsg struct {
	Ref     string   `json:"ref"`
	Preview *Preview `json:"preview"`
	Stale   bool     `json:"stale,omitempty"`
}

type IndexStatusMsg struct {
	Repos []RepoStatus `json:"repos"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v IndexStatusMsg) MarshalJSON() ([]byte, error) {
	type alias IndexStatusMsg
	a := alias(v)
	if a.Repos == nil {
		a.Repos = []RepoStatus{}
	}
	return json.Marshal(a)
}

type StateRestoreMsg struct {
	Text     string      `json:"text"`
	Recent   []string    `json:"recent"`
	Settings *UiSettings `json:"settings,omitempty"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v StateRestoreMsg) MarshalJSON() ([]byte, error) {
	type alias StateRestoreMsg
	a := alias(v)
	if a.Recent == nil {
		a.Recent = []string{}
	}
	return json.Marshal(a)
}

// UiSettings: The UI-facing settings the host forwards to the webview.
type UiSettings struct {
	TypingDelayMs   int    `json:"typingDelayMs"`
	OpenTrigger     string `json:"openTrigger"`
	Preview         bool   `json:"preview"`
	ShowParsedQuery bool   `json:"showParsedQuery"`
	CaseSensitive   bool   `json:"caseSensitive"`
}

// BannerMsg: Daemon health banner (failure table): restarting, stopped, or cleared.
type BannerMsg struct {
	State   string `json:"state"`
	Message string `json:"message,omitempty"`
}

// Contract 3 method names.
const (
	MethodInitialize              = "initialize"
	MethodWorkspaceSetRoots       = "workspace/setRoots"
	MethodWorkspaceDidChangeFiles = "workspace/didChangeFiles"
	MethodSettingsUpdate          = "settings/update"
	MethodQueryParse              = "query/parse"
	MethodSearchStart             = "search/start"
	MethodSearchBatch             = "search/batch"
	MethodDollarCancelRequest     = "$/cancelRequest"
	MethodPreviewGet              = "preview/get"
	MethodOpenResolve             = "open/resolve"
	MethodIndexStatus             = "index/status"
	MethodIndexProgress           = "index/progress"
	MethodIndexRebuild            = "index/rebuild"
	MethodShutdown                = "shutdown"
	MethodExit                    = "exit"
)

// Contract 2 message types.
const (
	MsgQueryChanged  = "query.changed"
	MsgResultSelect  = "result.select"
	MsgResultOpen    = "result.open"
	MsgResultsMore   = "results.more"
	MsgPanelClose    = "panel.close"
	MsgHelpOpen      = "help.open"
	MsgSettingsOpen  = "settings.open"
	MsgReady         = "ready"
	MsgDaemonRestart = "daemon.restart"
	MsgParseResult   = "parse.result"
	MsgSearchBatch   = "search.batch"
	MsgSearchDone    = "search.done"
	MsgPreviewResult = "preview.result"
	MsgIndexStatus   = "index.status"
	MsgStateRestore  = "state.restore"
	MsgBanner        = "banner"
	MsgFocus         = "focus"
)

// SpecMethods lists every Contract 3 method, for spec coverage.
var SpecMethods = []string{"initialize", "workspace/setRoots", "workspace/didChangeFiles", "settings/update", "query/parse", "search/start", "search/batch", "$/cancelRequest", "preview/get", "open/resolve", "index/status", "index/progress", "index/rebuild", "shutdown", "exit"}

// SpecMessages lists every Contract 2 message type, for spec coverage.
var SpecMessages = []string{"query.changed", "result.select", "result.open", "results.more", "panel.close", "help.open", "settings.open", "ready", "daemon.restart", "parse.result", "search.batch", "search.done", "preview.result", "index.status", "state.restore", "banner", "focus"}
