// Code generated by protocol/gen.mjs from protocol/protocol.schema.json. DO NOT EDIT.

package protocol

import "encoding/json"

// Version is the protocol version exchanged in initialize.
const Version = 1

// Application error codes carried in JSON-RPC error.code.
const (
	// CodeRequestCancelled: A newer keystroke cancelled this request.
	CodeRequestCancelled = -32800
	// CodeQueryInvalid: search/start got a query with error diagnostics.
	CodeQueryInvalid = 1001
	// CodeIndexNotReady: A repo has no index yet; partial results still stream.
	CodeIndexNotReady = 1002
	// CodeRefStale: The file or commit behind a ref is gone.
	CodeRefStale = 1003
	// CodeIndexCorrupt: A shard or database failed a check; a rebuild starts on its own.
	CodeIndexCorrupt = 1004
	// CodeOverloaded: The search hit its time budget and returned what it had.
	CodeOverloaded = 1005
)

// Span is a range of UTF-16 offsets into the raw query text.
type Span struct {
	Start int `json:"start"`
	End   int `json:"end"`
}

// MessageLine is one line of a commit message, with what the query's text terms match in it.
type MessageLine struct {
	Text string  `json:"text"`
	Hits []Range `json:"hits"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v MessageLine) MarshalJSON() ([]byte, error) {
	type plain MessageLine
	p := plain(v)
	if p.Hits == nil {
		p.Hits = []Range{}
	}
	return json.Marshal(p)
}

// Range is a range of UTF-16 offsets into the text shown on screen.
type Range struct {
	Start int `json:"start"`
	End   int `json:"end"`
}

// Hit is a matched Range plus the text term that matched, which picks its highlight color.
type Hit struct {
	Start     int `json:"start"`
	End       int `json:"end"`
	TermIndex int `json:"termIndex"`
}

// OpName is an operator's name, the part before the colon.
type OpName = string

// OpName values.
const (
	OpNameF      OpName = "f"
	OpNameRepo   OpName = "repo"
	OpNameLang   OpName = "lang"
	OpNameType   OpName = "type"
	OpNameSym    OpName = "sym"
	OpNameAuthor OpName = "author"
	OpNameMsg    OpName = "msg"
	OpNameSince  OpName = "since"
	OpNameCase   OpName = "case"
	OpNameCount  OpName = "count"
)

// Match says how a value was written: bare (literal), quoted (phrase), /regex/, or a path glob such as *.go (f: and repo: only).
type Match = string

// Match values.
const (
	MatchLiteral Match = "literal"
	MatchPhrase  Match = "phrase"
	MatchRegex   Match = "regex"
	MatchGlob    Match = "glob"
)

// Mode is what a query searches: current files or Git history.
type Mode = string

// Mode values.
const (
	ModeWorkingTree Mode = "workingTree"
	ModeHistory     Mode = "history"
)

// Severity is how serious a Diagnostic is; only errors stop a search.
type Severity = string

// Severity values.
const (
	SeverityError   Severity = "error"
	SeverityWarning Severity = "warning"
)

// TextEdit replaces a span of the query text.
type TextEdit struct {
	Span    Span   `json:"span"`
	NewText string `json:"newText"`
}

// Fix is a titled set of edits that repairs or rewrites the query.
type Fix struct {
	Title string     `json:"title"`
	Edits []TextEdit `json:"edits"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v Fix) MarshalJSON() ([]byte, error) {
	type plain Fix
	p := plain(v)
	if p.Edits == nil {
		p.Edits = []TextEdit{}
	}
	return json.Marshal(p)
}

// Diagnostic is a problem the parser found, with fixes the user can apply.
type Diagnostic struct {
	Severity Severity `json:"severity"`
	Code     string   `json:"code"`
	Message  string   `json:"message"`
	Span     Span     `json:"span"`
	Fixes    []Fix    `json:"fixes"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v Diagnostic) MarshalJSON() ([]byte, error) {
	type plain Diagnostic
	p := plain(v)
	if p.Fixes == nil {
		p.Fixes = []Fix{}
	}
	return json.Marshal(p)
}

// Resolved is a friendlier label for an operator value, such as an author's full name.
type Resolved struct {
	Label string `json:"label"`
}

// Node is one node of the parsed query tree.
type Node struct {
	Kind      string    `json:"kind,omitempty"`
	Children  []Node    `json:"children,omitempty"`
	Span      Span      `json:"span,omitempty"`
	Child     *Node     `json:"child,omitempty"`
	Value     string    `json:"value,omitempty"`
	Match     Match     `json:"match,omitempty"`
	TermIndex int       `json:"termIndex,omitempty"`
	Op        OpName    `json:"op,omitempty"`
	Resolved  *Resolved `json:"resolved,omitempty"`
}

// Node kinds: the values of Node.Kind.
const (
	NodeKindAnd  = "and"
	NodeKindOr   = "or"
	NodeKindNot  = "not"
	NodeKindText = "text"
	NodeKindOp   = "op"
)

// MarshalJSON emits only the fields of the variant named by Kind.
func (v Node) MarshalJSON() ([]byte, error) {
	fields := map[string]any{"kind": v.Kind}
	switch v.Kind {
	case "and", "or":
		if v.Children == nil {
			fields["children"] = []Node{}
		} else {
			fields["children"] = v.Children
		}
		fields["span"] = v.Span
	case "not":
		fields["child"] = v.Child
		fields["span"] = v.Span
	case "text":
		fields["value"] = v.Value
		fields["match"] = v.Match
		fields["termIndex"] = v.TermIndex
		fields["span"] = v.Span
	case "op":
		fields["op"] = v.Op
		fields["value"] = v.Value
		fields["match"] = v.Match
		fields["span"] = v.Span
		if v.Resolved != nil {
			fields["resolved"] = v.Resolved
		}
	}
	return json.Marshal(fields)
}

// Globals are the query-wide operators case:, count: and type:, or null when absent.
type Globals struct {
	Case  *string `json:"case"`
	Count any     `json:"count"`
	Type  *string `json:"type"`
}

// ParsedQuery is the parser's output: the query tree, its global operators and its diagnostics.
type ParsedQuery struct {
	Version     int          `json:"version"`
	Raw         string       `json:"raw"`
	Root        *Node        `json:"root"`
	Globals     Globals      `json:"globals"`
	Mode        Mode         `json:"mode"`
	Diagnostics []Diagnostic `json:"diagnostics"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v ParsedQuery) MarshalJSON() ([]byte, error) {
	type plain ParsedQuery
	p := plain(v)
	if p.Diagnostics == nil {
		p.Diagnostics = []Diagnostic{}
	}
	return json.Marshal(p)
}

// Root is a workspace folder; its id is the first 12 hex digits of sha256(path).
type Root struct {
	ID   string `json:"id"`
	Path string `json:"path"`
	Name string `json:"name"`
}

// Settings are the unifiedSearch.* settings the daemon needs.
type Settings struct {
	CaseSensitive  bool     `json:"caseSensitive"`
	DefaultCount   int      `json:"defaultCount"`
	HistoryDepth   string   `json:"historyDepth"`
	Symbols        bool     `json:"symbols"`
	Exclude        []string `json:"exclude"`
	IncludeIgnored bool     `json:"includeIgnored"`
	MaxFileSizeKB  int      `json:"maxFileSizeKB"`
	Location       string   `json:"location"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v Settings) MarshalJSON() ([]byte, error) {
	type plain Settings
	p := plain(v)
	if p.Exclude == nil {
		p.Exclude = []string{}
	}
	return json.Marshal(p)
}

// LastCommit is the newest commit that touched a file.
type LastCommit struct {
	SHA    string `json:"sha"`
	Author string `json:"author"`
	At     string `json:"at"`
}

// Person is a commit author.
type Person struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

// FileStat is one file changed by a commit.
type FileStat struct {
	Path           string `json:"path"`
	Added          int    `json:"added"`
	Removed        int    `json:"removed"`
	HiddenByFilter bool   `json:"hiddenByFilter,omitempty"`
}

// SymbolKind is what a symbol definition is.
type SymbolKind = string

// SymbolKind values.
const (
	SymbolKindClass     SymbolKind = "class"
	SymbolKindInterface SymbolKind = "interface"
	SymbolKindFunction  SymbolKind = "function"
	SymbolKindMethod    SymbolKind = "method"
	SymbolKindType      SymbolKind = "type"
	SymbolKindOther     SymbolKind = "other"
)

// ResultItem is one search result: a file name, a code line, a symbol or a commit.
type ResultItem struct {
	Kind         string       `json:"kind,omitempty"`
	Ref          string       `json:"ref,omitempty"`
	RepoID       string       `json:"repoId,omitempty"`
	Path         string       `json:"path,omitempty"`
	NameHits     []Range      `json:"nameHits,omitempty"`
	LastCommit   *LastCommit  `json:"lastCommit,omitempty"`
	Dirty        bool         `json:"dirty,omitempty"`
	Line         int          `json:"line,omitempty"`
	Text         string       `json:"text,omitempty"`
	Hits         []Hit        `json:"hits,omitempty"`
	Name         string       `json:"name,omitempty"`
	SymbolKind   SymbolKind   `json:"symbolKind,omitempty"`
	SHA          string       `json:"sha,omitempty"`
	Subject      string       `json:"subject,omitempty"`
	Author       Person       `json:"author,omitempty"`
	At           string       `json:"at,omitempty"`
	Files        []FileStat   `json:"files,omitempty"`
	DiffHits     int          `json:"diffHits,omitempty"`
	MatchedTerms []int        `json:"matchedTerms,omitempty"`
	SubjectHits  []Range      `json:"subjectHits,omitempty"`
	InMessage    bool         `json:"inMessage,omitempty"`
	BodyLine     *MessageLine `json:"bodyLine,omitempty"`
}

// ResultItem kinds: the values of ResultItem.Kind.
const (
	ResultItemKindFile   = "file"
	ResultItemKindLine   = "line"
	ResultItemKindSymbol = "symbol"
	ResultItemKindCommit = "commit"
)

// MarshalJSON emits only the fields of the variant named by Kind.
func (v ResultItem) MarshalJSON() ([]byte, error) {
	fields := map[string]any{"kind": v.Kind}
	switch v.Kind {
	case "file":
		fields["ref"] = v.Ref
		fields["repoId"] = v.RepoID
		fields["path"] = v.Path
		if v.NameHits == nil {
			fields["nameHits"] = []Range{}
		} else {
			fields["nameHits"] = v.NameHits
		}
		if v.LastCommit != nil {
			fields["lastCommit"] = v.LastCommit
		}
		fields["dirty"] = v.Dirty
	case "line":
		fields["ref"] = v.Ref
		fields["repoId"] = v.RepoID
		fields["path"] = v.Path
		fields["line"] = v.Line
		fields["text"] = v.Text
		if v.Hits == nil {
			fields["hits"] = []Hit{}
		} else {
			fields["hits"] = v.Hits
		}
	case "symbol":
		fields["ref"] = v.Ref
		fields["repoId"] = v.RepoID
		fields["path"] = v.Path
		fields["line"] = v.Line
		fields["name"] = v.Name
		fields["symbolKind"] = v.SymbolKind
		if v.Hits == nil {
			fields["hits"] = []Hit{}
		} else {
			fields["hits"] = v.Hits
		}
	case "commit":
		fields["ref"] = v.Ref
		fields["repoId"] = v.RepoID
		fields["sha"] = v.SHA
		fields["subject"] = v.Subject
		fields["author"] = v.Author
		fields["at"] = v.At
		if v.Files == nil {
			fields["files"] = []FileStat{}
		} else {
			fields["files"] = v.Files
		}
		fields["diffHits"] = v.DiffHits
		if v.MatchedTerms == nil {
			fields["matchedTerms"] = []int{}
		} else {
			fields["matchedTerms"] = v.MatchedTerms
		}
		if v.SubjectHits == nil {
			fields["subjectHits"] = []Range{}
		} else {
			fields["subjectHits"] = v.SubjectHits
		}
		fields["inMessage"] = v.InMessage
		if v.BodyLine != nil {
			fields["bodyLine"] = v.BodyLine
		}
	}
	return json.Marshal(fields)
}

// LineHits are the matches on one preview line.
type LineHits struct {
	Line   int   `json:"line"`
	Ranges []Hit `json:"ranges"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v LineHits) MarshalJSON() ([]byte, error) {
	type plain LineHits
	p := plain(v)
	if p.Ranges == nil {
		p.Ranges = []Hit{}
	}
	return json.Marshal(p)
}

// OutlineSymbol is a definition shown in a file preview's outline.
type OutlineSymbol struct {
	Name string `json:"name"`
	Line int    `json:"line"`
}

// DiffLine is one line of a diff hunk.
type DiffLine struct {
	Kind  string `json:"kind"`
	OldNo int    `json:"oldNo,omitempty"`
	NewNo int    `json:"newNo,omitempty"`
	Text  string `json:"text"`
	Hits  []Hit  `json:"hits"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v DiffLine) MarshalJSON() ([]byte, error) {
	type plain DiffLine
	p := plain(v)
	if p.Hits == nil {
		p.Hits = []Hit{}
	}
	return json.Marshal(p)
}

// Hunk is one hunk of a commit diff.
type Hunk struct {
	Path   string     `json:"path"`
	Header string     `json:"header"`
	Lines  []DiffLine `json:"lines"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v Hunk) MarshalJSON() ([]byte, error) {
	type plain Hunk
	p := plain(v)
	if p.Lines == nil {
		p.Lines = []DiffLine{}
	}
	return json.Marshal(p)
}

// Preview is the right-hand pane's content for a selected result.
type Preview struct {
	Kind        string          `json:"kind,omitempty"`
	Path        string          `json:"path,omitempty"`
	FirstLine   int             `json:"firstLine,omitempty"`
	Lines       []string        `json:"lines,omitempty"`
	FocusLine   int             `json:"focusLine,omitempty"`
	Hits        []LineHits      `json:"hits,omitempty"`
	DirtyLines  []int           `json:"dirtyLines,omitempty"`
	Symbols     []OutlineSymbol `json:"symbols,omitempty"`
	SHA         string          `json:"sha,omitempty"`
	Subject     string          `json:"subject,omitempty"`
	Body        string          `json:"body,omitempty"`
	Author      string          `json:"author,omitempty"`
	At          string          `json:"at,omitempty"`
	Files       []FileStat      `json:"files,omitempty"`
	Hunks       []Hunk          `json:"hunks,omitempty"`
	SubjectHits []Range         `json:"subjectHits,omitempty"`
	BodyHits    []Range         `json:"bodyHits,omitempty"`
}

// Preview kinds: the values of Preview.Kind.
const (
	PreviewKindFile   = "file"
	PreviewKindCommit = "commit"
)

// MarshalJSON emits only the fields of the variant named by Kind.
func (v Preview) MarshalJSON() ([]byte, error) {
	fields := map[string]any{"kind": v.Kind}
	switch v.Kind {
	case "file":
		fields["path"] = v.Path
		fields["firstLine"] = v.FirstLine
		if v.Lines == nil {
			fields["lines"] = []string{}
		} else {
			fields["lines"] = v.Lines
		}
		fields["focusLine"] = v.FocusLine
		if v.Hits == nil {
			fields["hits"] = []LineHits{}
		} else {
			fields["hits"] = v.Hits
		}
		if v.DirtyLines == nil {
			fields["dirtyLines"] = []int{}
		} else {
			fields["dirtyLines"] = v.DirtyLines
		}
		if len(v.Symbols) > 0 {
			fields["symbols"] = v.Symbols
		}
	case "commit":
		fields["sha"] = v.SHA
		fields["subject"] = v.Subject
		fields["body"] = v.Body
		fields["author"] = v.Author
		fields["at"] = v.At
		if v.Files == nil {
			fields["files"] = []FileStat{}
		} else {
			fields["files"] = v.Files
		}
		if v.Hunks == nil {
			fields["hunks"] = []Hunk{}
		} else {
			fields["hunks"] = v.Hunks
		}
		if v.SubjectHits == nil {
			fields["subjectHits"] = []Range{}
		} else {
			fields["subjectHits"] = v.SubjectHits
		}
		if v.BodyHits == nil {
			fields["bodyHits"] = []Range{}
		} else {
			fields["bodyHits"] = v.BodyHits
		}
	}
	return json.Marshal(fields)
}

// HiddenNote counts results a filter removed, with a fix that removes the filter.
type HiddenNote struct {
	Reason string `json:"reason"`
	// Filter is the filter as typed, e.g. -f:vendor/
	Filter string `json:"filter"`
	Count  int    `json:"count"`
	Unit   string `json:"unit"`
	Undo   Fix    `json:"undo"`
}

// Completion is an autocomplete suggestion; accepting it applies its edit.
type Completion struct {
	Label string `json:"label"`
	// Detail is what the suggestion means, in a few words: "Last 2 hours", "Python files".
	Detail string `json:"detail"`
	// Context is facts that help choose it, on a second line: "Since 08:04", "14 files · payments-api, web-checkout".
	Context string `json:"context,omitempty"`
	// Note is a short status shown at the end of the row: "5 files changed", "Indexing 64%".
	Note string `json:"note,omitempty"`
	// Section is a heading shown above this suggestion; the suggestions after it, up to the next section, belong under it.
	Section string `json:"section,omitempty"`
	Insert  Fix    `json:"insert"`
	Group   string `json:"group"`
}

// IndexState is where one index of a repo stands.
type IndexState = string

// IndexState values.
const (
	IndexStateReady    IndexState = "ready"
	IndexStateIndexing IndexState = "indexing"
	IndexStateQueued   IndexState = "queued"
	IndexStateError    IndexState = "error"
	IndexStateOff      IndexState = "off"
)

// RepoStatus is the indexing state of one repo.
type RepoStatus struct {
	RepoID   string     `json:"repoId"`
	Name     string     `json:"name"`
	Tree     IndexState `json:"tree"`
	History  IndexState `json:"history"`
	Progress float64    `json:"progress,omitempty"`
	Message  string     `json:"message,omitempty"`
}

// OpenTarget is where opening a result goes: a file position (path, line, column, length) or a commit (repoId, sha).
type OpenTarget struct {
	Path   string `json:"path,omitempty"`
	Line   int    `json:"line,omitempty"`
	Column int    `json:"column,omitempty"`
	Length int    `json:"length,omitempty"`
	RepoID string `json:"repoId,omitempty"`
	SHA    string `json:"sha,omitempty"`
}

// OpenWhere is which editor group a result opens in.
type OpenWhere = string

// OpenWhere values.
const (
	OpenWhereCurrent OpenWhere = "current"
	OpenWhereSide    OpenWhere = "side"
)

// InitializeParams start the daemon.
type InitializeParams struct {
	Protocol int      `json:"protocol"`
	Roots    []Root   `json:"roots"`
	Settings Settings `json:"settings"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v InitializeParams) MarshalJSON() ([]byte, error) {
	type plain InitializeParams
	p := plain(v)
	if p.Roots == nil {
		p.Roots = []Root{}
	}
	return json.Marshal(p)
}

// InitializeResult reports the daemon's version and protocol.
type InitializeResult struct {
	DaemonVersion string `json:"daemonVersion"`
	Protocol      int    `json:"protocol"`
}

// SetRootsParams replace the workspace folders.
type SetRootsParams struct {
	Roots []Root `json:"roots"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SetRootsParams) MarshalJSON() ([]byte, error) {
	type plain SetRootsParams
	p := plain(v)
	if p.Roots == nil {
		p.Roots = []Root{}
	}
	return json.Marshal(p)
}

// SettingsUpdateParams carry changed settings.
type SettingsUpdateParams struct {
	Settings Settings `json:"settings"`
}

// FileChange is one file event from VS Code's watcher.
type FileChange struct {
	Path string `json:"path"`
	Type string `json:"type"`
}

// DidChangeFilesParams forward file events from the host, a fast path ahead of the daemon's own watcher.
type DidChangeFilesParams struct {
	Changes []FileChange `json:"changes"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v DidChangeFilesParams) MarshalJSON() ([]byte, error) {
	type plain DidChangeFilesParams
	p := plain(v)
	if p.Changes == nil {
		p.Changes = []FileChange{}
	}
	return json.Marshal(p)
}

// ParseParams ask the daemon to parse the query box.
type ParseParams struct {
	Text   string `json:"text"`
	Cursor int    `json:"cursor"`
}

// ParseResult is the parsed query plus completions at the cursor.
type ParseResult struct {
	Query       ParsedQuery  `json:"query"`
	Completions []Completion `json:"completions"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v ParseResult) MarshalJSON() ([]byte, error) {
	type plain ParseResult
	p := plain(v)
	if p.Completions == nil {
		p.Completions = []Completion{}
	}
	return json.Marshal(p)
}

// SearchStartParams start (or page) a search; the daemon re-parses the text itself.
type SearchStartParams struct {
	SearchID string `json:"searchId"`
	Text     string `json:"text"`
	Cursor   string `json:"cursor,omitempty"`
}

// SearchResult ends a search after its batches.
type SearchResult struct {
	Total      int          `json:"total"`
	Truncated  bool         `json:"truncated"`
	NextCursor string       `json:"nextCursor,omitempty"`
	Hidden     []HiddenNote `json:"hidden"`
	Ms         int          `json:"ms"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SearchResult) MarshalJSON() ([]byte, error) {
	type plain SearchResult
	p := plain(v)
	if p.Hidden == nil {
		p.Hidden = []HiddenNote{}
	}
	return json.Marshal(p)
}

// SearchBatchParams stream up to 200 results of a running search.
type SearchBatchParams struct {
	SearchID string       `json:"searchId"`
	Items    []ResultItem `json:"items"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SearchBatchParams) MarshalJSON() ([]byte, error) {
	type plain SearchBatchParams
	p := plain(v)
	if p.Items == nil {
		p.Items = []ResultItem{}
	}
	return json.Marshal(p)
}

// PreviewParams ask for the preview of a result.
type PreviewParams struct {
	Ref          string `json:"ref"`
	ContextLines int    `json:"contextLines"`
}

// OpenResolveParams ask where a result opens.
type OpenResolveParams struct {
	Ref string `json:"ref"`
}

// IndexStatusResult is the indexing state of every repo.
type IndexStatusResult struct {
	Repos []RepoStatus `json:"repos"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v IndexStatusResult) MarshalJSON() ([]byte, error) {
	type plain IndexStatusResult
	p := plain(v)
	if p.Repos == nil {
		p.Repos = []RepoStatus{}
	}
	return json.Marshal(p)
}

// RebuildParams name the repo to rebuild, or all when repoId is absent.
type RebuildParams struct {
	RepoID string `json:"repoId,omitempty"`
}

// Empty is a message with no fields.
type Empty struct {
}

// Envelope wraps every message between the webview and the extension host, in both directions.
type Envelope struct {
	V       int             `json:"v"`
	Type    string          `json:"type"`
	Seq     int             `json:"seq,omitempty"`
	Payload json.RawMessage `json:"payload"`
}

// QueryChangedMsg reports the query box after the typing delay.
type QueryChangedMsg struct {
	Text   string `json:"text"`
	Cursor int    `json:"cursor"`
	Seq    int    `json:"seq"`
	// AsTyped is true when the user dismissed the suggestions (Esc or Enter): search the box exactly as typed, including the word at the cursor.
	AsTyped bool `json:"asTyped,omitempty"`
}

// ResultSelectMsg asks for a result's preview.
type ResultSelectMsg struct {
	Ref string `json:"ref"`
}

// ResultOpenMsg opens a result in an editor.
type ResultOpenMsg struct {
	Ref   string    `json:"ref"`
	Where OpenWhere `json:"where"`
}

// ResultsMoreMsg loads the next page of results.
type ResultsMoreMsg struct {
	SearchID string `json:"searchId"`
	Cursor   string `json:"cursor"`
}

// HelpTryMsg runs an example from the help page in the search panel.
type HelpTryMsg struct {
	Query string `json:"query"`
}

// RecentRemoveMsg removes a query from the recent list.
type RecentRemoveMsg struct {
	Query string `json:"query"`
}

// WelcomeStateMsg is what the welcome page shows: the shortcut preset and what is indexed.
type WelcomeStateMsg struct {
	Preset       string `json:"preset"`
	HistoryDepth string `json:"historyDepth"`
	Symbols      bool   `json:"symbols"`
	// Mac is whether keys are written for a Mac (⌘P) or for Windows and Linux (Ctrl+P)
	Mac bool `json:"mac"`
}

// WelcomeChooseMsg saves one choice made on the welcome page in the user's settings.
type WelcomeChooseMsg struct {
	Preset       string `json:"preset,omitempty"`
	HistoryDepth string `json:"historyDepth,omitempty"`
	Symbols      bool   `json:"symbols,omitempty"`
}

// ParseResultMsg drives the chips, diagnostics, completions and toggles.
type ParseResultMsg struct {
	Seq         int          `json:"seq"`
	Query       ParsedQuery  `json:"query"`
	Completions []Completion `json:"completions"`
	// SearchText is the text the search runs on when it leaves out the word being completed ("Results for timeout keep updating"). Absent when the whole box is searched.
	SearchText string `json:"searchText,omitempty"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v ParseResultMsg) MarshalJSON() ([]byte, error) {
	type plain ParseResultMsg
	p := plain(v)
	if p.Completions == nil {
		p.Completions = []Completion{}
	}
	return json.Marshal(p)
}

// SearchBatchMsg appends streamed results.
type SearchBatchMsg struct {
	Seq      int          `json:"seq"`
	SearchID string       `json:"searchId"`
	Items    []ResultItem `json:"items"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SearchBatchMsg) MarshalJSON() ([]byte, error) {
	type plain SearchBatchMsg
	p := plain(v)
	if p.Items == nil {
		p.Items = []ResultItem{}
	}
	return json.Marshal(p)
}

// SearchDoneMsg ends a search: counts, hidden notes, Load more and errors.
type SearchDoneMsg struct {
	Seq        int          `json:"seq"`
	SearchID   string       `json:"searchId"`
	Total      int          `json:"total"`
	Truncated  bool         `json:"truncated"`
	NextCursor string       `json:"nextCursor,omitempty"`
	Hidden     []HiddenNote `json:"hidden"`
	Ms         int          `json:"ms"`
	Error      string       `json:"error,omitempty"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v SearchDoneMsg) MarshalJSON() ([]byte, error) {
	type plain SearchDoneMsg
	p := plain(v)
	if p.Hidden == nil {
		p.Hidden = []HiddenNote{}
	}
	return json.Marshal(p)
}

// PreviewResultMsg fills the preview pane; stale means the result no longer exists.
type PreviewResultMsg struct {
	Ref     string   `json:"ref"`
	Preview *Preview `json:"preview"`
	Stale   bool     `json:"stale,omitempty"`
}

// IndexStatusMsg drives the header dot and indexing banners.
type IndexStatusMsg struct {
	Repos []RepoStatus `json:"repos"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v IndexStatusMsg) MarshalJSON() ([]byte, error) {
	type plain IndexStatusMsg
	p := plain(v)
	if p.Repos == nil {
		p.Repos = []RepoStatus{}
	}
	return json.Marshal(p)
}

// StateRestoreMsg restores the panel's query, recent queries and settings.
type StateRestoreMsg struct {
	Text     string      `json:"text"`
	Recent   []string    `json:"recent"`
	Settings *UiSettings `json:"settings,omitempty"`
}

// MarshalJSON emits [] rather than null for required arrays.
func (v StateRestoreMsg) MarshalJSON() ([]byte, error) {
	type plain StateRestoreMsg
	p := plain(v)
	if p.Recent == nil {
		p.Recent = []string{}
	}
	return json.Marshal(p)
}

// UiSettings are the UI-facing settings the host forwards to the webview.
type UiSettings struct {
	TypingDelayMs   int    `json:"typingDelayMs"`
	OpenTrigger     string `json:"openTrigger"`
	Preview         bool   `json:"preview"`
	ShowParsedQuery bool   `json:"showParsedQuery"`
	CaseSensitive   bool   `json:"caseSensitive"`
}

// BannerMsg reports daemon health: restarting, stopped or cleared.
type BannerMsg struct {
	State   string `json:"state"`
	Message string `json:"message,omitempty"`
}

// Daemon JSON-RPC method names.
const (
	MethodInitialize              = "initialize"
	MethodWorkspaceSetRoots       = "workspace/setRoots"
	MethodWorkspaceDidChangeFiles = "workspace/didChangeFiles"
	MethodSettingsUpdate          = "settings/update"
	MethodQueryParse              = "query/parse"
	MethodSearchStart             = "search/start"
	MethodSearchBatch             = "search/batch"
	MethodDollarCancelRequest     = "$/cancelRequest"
	MethodPreviewGet              = "preview/get"
	MethodOpenResolve             = "open/resolve"
	MethodIndexStatus             = "index/status"
	MethodIndexProgress           = "index/progress"
	MethodIndexRebuild            = "index/rebuild"
	MethodShutdown                = "shutdown"
	MethodExit                    = "exit"
)

// Search panel message types (webview <-> extension host).
const (
	MsgQueryChanged    = "query.changed"
	MsgResultSelect    = "result.select"
	MsgResultOpen      = "result.open"
	MsgResultsMore     = "results.more"
	MsgPanelClose      = "panel.close"
	MsgHelpOpen        = "help.open"
	MsgHelpTry         = "help.try"
	MsgSettingsOpen    = "settings.open"
	MsgWelcomeChoose   = "welcome.choose"
	MsgWelcomeShortcut = "welcome.shortcut"
	MsgWelcomeStart    = "welcome.start"
	MsgReady           = "ready"
	MsgDaemonRestart   = "daemon.restart"
	MsgRecentRemove    = "recent.remove"
	MsgParseResult     = "parse.result"
	MsgSearchBatch     = "search.batch"
	MsgSearchDone      = "search.done"
	MsgPreviewResult   = "preview.result"
	MsgIndexStatus     = "index.status"
	MsgStateRestore    = "state.restore"
	MsgBanner          = "banner"
	MsgFocus           = "focus"
	MsgWelcomeState    = "welcome.state"
)
